import { NextResponse } from "next/server";
import { getCalendarRuntime } from "@/lib/calendar-config";
import { getHandoffEmailRuntime } from "@/lib/handoff-email";
import { getOpenAiWhatsAppReplyRuntime } from "@/lib/openai-whatsapp-config";
import { getOptionalAiSalesBrainRuntime } from "@/lib/whatsapp-v6/sales-brain";
import { getLimmInstagramUrl } from "@/lib/whatsapp-lead-context";
import { singaporeOfficialPlanningAreaMapAvailable } from "@/lib/singapore-map-geometry";
import { questionBankStats } from "@/lib/whatsapp-question-bank";
import { getClientFilesStorageRuntime } from "@/lib/data/lead-files-repository";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

// Version-history markers kept so older static phase checks can still verify the v6.3 layer:
// version: "v6_3_sales_collection_command_centre"
// salesBrainVersion: "v6.3"
// version: "v6_4_singapore_mission_map"
// salesBrainVersion: "v6.4"
// version: "v6_4_1_singapore_tactical_map_ui_polish"
// salesBrainVersion: "v6.4.1"
// version: "v6_4_2_accurate_singapore_map_no_overlay"
// salesBrainVersion: "v6.4.2"
// version: "v6_4_3_singapore_map_zoom_hq_redesign"
// salesBrainVersion: "v6.4.3"
// version: "v6_4_4_accurate_singapore_svg_map_fix"
// salesBrainVersion: "v6.4.4"
// version: "v6_4_5_real_singapore_geojson_map"
// salesBrainVersion: "v6.4.5"
// version: "v6_4_6_official_singapore_planning_area_map"
// salesBrainVersion: "v6.4.6"
// version: "v6_4_8_singapore_map_interaction_final_polish"
// salesBrainVersion: "v6.4.8"
// version: "v6_4_9_singapore_map_smooth_zoom_wheel_lock"
// salesBrainVersion: "v6.4.9"
// version: "v6_4_10_singapore_map_interaction_copy_cleanup"
// salesBrainVersion: "v6.4.10"
// version: "v6_5_smart_lead_intake_meeting_prep"
// salesBrainVersion: "v6.5"
// version: "v6_5_1_accurate_singapore_map_refinement"
// salesBrainVersion: "v6.5.1"
// version: "v6_ui_100_command_centre_polish"
// version: "v6_6_strategic_command_core_layout"
// version: "v6_6_1_strategic_command_core_ui_fit_polish"
// version: "v6_6_2_command_core_map_first_layout"
// version: "v6_6_3_strategic_command_core_final_touchup"
// version: "v6_7_real_client_file_upload_whatsapp_media_storage"
// salesBrainVersion: "v6.7"
// version: "v6_7_1_whatsapp_final_safety_false_positive_fix"
// salesBrainVersion: "v6.7.1"
// version: "v6_5_1_intake_memory_budget_statement_fix"
// version: "v7_world_class_whatsapp_sales_brain"
// salesBrainVersion: "v7"

function envPresent(name: string) {
  return Boolean(process.env[name]);
}

function envFlag(name: string, fallback = false) {
  const value = process.env[name];
  if (value === undefined || value === "") return fallback;
  return value.toLowerCase() === "true";
}

export async function GET() {
  try {
    const openAiWhatsApp = getOpenAiWhatsAppReplyRuntime();
    const optionalAiSalesBrain = getOptionalAiSalesBrainRuntime();
    const calendar = getCalendarRuntime();
    const handoffEmail = getHandoffEmailRuntime();
    const questionBank = questionBankStats();
    const instagramUrlConfigured = Boolean(getLimmInstagramUrl());
    const clientFilesStorage = getClientFilesStorageRuntime();
    const officialSingaporePlanningAreaMapAvailable = singaporeOfficialPlanningAreaMapAvailable();
    return NextResponse.json({
      ok: true,
      version: "v7_world_class_whatsapp_sales_brain",
      salesBrainVersion: "v7",
      runtime: "vercel",
      worldClassSalesConversationBrainAvailable: true,
      memoryFirstReplyComposerAvailable: true,
      knownInfoAcknowledgementBeforeQuestions: true,
      shortPingSmartReplyAvailable: true,
      confusionPingSmartReplyAvailable: true,
      alreadyToldYouRecoveryAvailable: true,
      budgetStatementNotPriceQuestionAvailable: true,
      contextAwareMissingInfoQuestionsAvailable: true,
      maxThreeQuestionsDefaultAvailable: true,
      genericFallbackReducedAvailable: true,
      conversationReplayTestAvailable: true,
      intakeKnownInfoAcknowledgementAvailable: true,
      budgetStatementClassificationAvailable: true,
      budgetExpectationNotPriceQuestionAvailable: true,
      intakeMissingInfoDeduplicationAvailable: true,
      addressExtractionAvailable: true,
      timelineExtractionAvailable: true,
      landedAaExtractionAvailable: true,
      finalSafetyFalsePositiveFixAvailable: true,
      safeFallbackFinalValidationAllowed: true,
      ultraSafeFallbackRewriteAvailable: true,
      finalValidationReasonLoggingAvailable: true,
      clientFileStorageAvailable: true,
      supabaseClientFilesBucketConfigured: Boolean(clientFilesStorage.bucketName),
      leadFilesTableAvailable: true,
      whatsappMediaStorageAvailable: true,
      whatsappImageStorageAvailable: true,
      whatsappDocumentStorageAvailable: true,
      clientUploadLinkAvailable: true,
      secureUploadTokenAvailable: true,
      leadDetailFilePanelAvailable: true,
      clientFilesPageRealDataAvailable: true,
      signedFileUrlAvailable: true,
      fileCategoryDetectionAvailable: true,
      fileStatusTrackingAvailable: true,
      fileReviewWorkflowAvailable: true,
      fileVoidInsteadOfDeleteAvailable: true,
      fileUploadAuditAvailable: true,
      meetingReadinessFileConnectionAvailable: true,
      quotationReadinessFileConnectionAvailable: true,
      strategicCommandCoreAvailable: true,
      commandCoreBetaRouteAvailable: true,
      frostpunkInspiredLayoutAvailable: true,
      commandCoreFinalTouchupAvailable: true,
      commandCoreResourceBarContrastFixed: true,
      commandCoreOperatingPictureCompressed: true,
      commandCoreMapHeroPreserved: true,
      commandCoreBottomPanelsAligned: true,
      commandCoreMapFirstLayoutAvailable: true,
      commandCoreMapFullWidthHeroAvailable: true,
      commandCoreMapSameSizeAsDashboardAvailable: true,
      commandCoreResourceBarReadable: true,
      commandCorePaleResourceCardsRemoved: true,
      commandCoreSidePanelsNoLongerSqueezeMap: true,
      commandCoreWideMapLayoutAvailable: true,
      commandCoreMapDominantLayoutAvailable: true,
      commandCoreMapUsesFullPanelWidth: true,
      topResourceBarAvailable: true,
      marcusDecisionsPanelAvailable: true,
      rightInspectorPanelAvailable: true,
      bottomTimelineStripAvailable: true,
      commandCoreUsesRealDataOnly: true,
      currentDashboardPreserved: true,
      ui100CommandCentrePolishAvailable: true,
      dashboardBossActionClarityAvailable: true,
      marcusToday100PolishAvailable: true,
      leadCards100PolishAvailable: true,
      sidebar100PolishAvailable: true,
      followUpQueueUiPreserved: true,
      leadDetail100PolishAvailable: true,
      emptyStates100PolishAvailable: true,
      mobileUiPolishAvailable: true,
      interactionFeedbackPolishAvailable: true,
      performanceSafeUiPolishAvailable: true,
      officialSingaporeMapPreserved: true,
      mapDefaultZoomStartsAt100: true,
      mapSmoothZoomControlsAvailable: true,
      mapResetClearsPanSelectionTooltip: true,
      mapWheelZoomAvailable: true,
      mapWheelPreventsPageScroll: true,
      mapWheelListenerPassiveFalse: true,
      mapDefaultFitImproved: true,
      mapHorizontalSpaceOptimized: true,
      mapResetClearsSelection: true,
      mapFilterEmptyStatePolished: true,
      mapTopLeftCopyDeduped: true,
      mapHelperTextMovedToBottom: true,
      mapNoStackedStatusLabels: true,
      mapInspectorPanelAvailable: true,
      mapHqMarkerScalePolished: true,
      mapResetButtonFixed: true,
      mapResetRestoresDefaultFit: true,
      mapZoomControlsReliable: true,
      mapZoomBoundsAvailable: true,
      mapZoomPercentAccurate: true,
      mapPanDragAvailable: true,
      mapResetClearsPanAndSelection: true,
      mapAreaClickSummaryAvailable: true,
      mapPinClickSummaryAvailable: true,
      mapHqTooltipAvailable: true,
      mapAreaCountBubblesAvailable: true,
      mapFiltersAffectPinsAvailable: true,
      officialMapGeometryPreserved: true,
      officialSingaporePlanningAreaMapAvailable,
      mapFitToBoundsAvailable: true,
      mapCroppingFixed: true,
      areaLabelsBoundedToPolygons: true,
      hqMarkerCentralSingaporeAvailable: true,
      fakeSentosaRemoved: true,
      realSingaporeGeojsonMapAvailable: true,
      realMapGeometryAssetAvailable: true,
      manualBlobMapRemoved: true,
      hqMarkerPostal228397Available: true,
      googleMapsEnabled: false,
      realSingaporeOutlineAvailable: true,
      hqMarkerCentralSingaporeCalibrated: true,
      sentosaScaledShapeRefined: false,
      mapAreaLabelsAvailable: true,
      largeMapHelperBoxRemoved: true,
      smartLeadIntakeAvailable: true,
      meetingPrepBrainAvailable: true,
      lifestyleIntakeAvailable: true,
      householdOccupantsIntakeAvailable: true,
      helperPetsIntakeAvailable: true,
      safetyAccessibilityIntakeAvailable: true,
      budgetExpectationCaptureAvailable: true,
      timelineKeyMoveInCaptureAvailable: true,
      intakeChecklistAvailable: true,
      missingInfoDetectorAvailable: true,
      intakeQuestionLimitAvailable: true,
      maxFiveQuestionsRuleAvailable: true,
      noOverlyTechnicalFirstContactQuestions: true,
      intakeQuestionLimitMin: 3,
      intakeQuestionLimitMax: 5,
      lifestyleOccupantsPetsSafetyAvailable: true,
      budgetExpectationCollectionNoPriceReply: true,
      timelineKeyMoveInCollectionAvailable: true,
      meetingReadinessScoreAvailable: true,
      proposalReadinessScoreAvailable: true,
      leadIntakeProfileStorageAvailable: true,
      leadIntakeAuditTraceAvailable: true,
      accurateSingaporeSvgMapAvailable: true,
      singaporeMainlandSvgAvailable: true,
      sentosaOnlyIslandAvailable: false,
      singaporeMapWideLayoutAvailable: true,
      singaporeMapZoomableAvailable: true,
      singaporeMapPanAvailable: true,
      singaporeMapResetZoomAvailable: true,
      singaporeMapHqMarkerAvailable: true,
      singaporeMapHqPostalCode: "228397",
      singaporeMapSentosaOnlyAvailable: false,
      goldAmberColourSeparationFixed: true,
      accurateSingaporeMapAvailable: true,
      mapNoBlockingOverlayAvailable: true,
      mapBaseAlwaysVisible: true,
      subtleEmptyStateHelperAvailable: true,
      singaporeTacticalMapUiAvailable: true,
      singaporeSilhouetteMapAvailable: true,
      mapEmptyStatePolished: true,
      mapLegendIntegrated: true,
      mapAreaSummaryPanelAvailable: true,
      singaporeMissionMapAvailable: true,
      hybridAreaHeatmapAvailable: true,
      clickableMapPinsAvailable: true,
      mapAreaSummaryAvailable: true,
      mapFiltersAvailable: true,
      privacySafeMapDisplayAvailable: true,
      locationConfidenceAvailable: true,
      localSingaporeLocationParserAvailable: true,
      externalGeocodingEnabled: false,
      mapHidesTestDataByDefault: true,
      salesCollectionMapLayerAvailable: true,
      salesPipelineAvailable: true,
      manualQuotationTrackingAvailable: true,
      monthlySalesTargetsAvailable: true,
      monthlyCollectionTargetsAvailable: true,
      potentialQuotedConfirmedValuesAvailable: true,
      wonLostTrackingAvailable: true,
      leadToProjectConversionAvailable: true,
      paymentCollectionTrackerAvailable: true,
      outstandingReceivablesAvailable: true,
      overdueReceivablesAvailable: true,
      quotationPaymentFollowUpRemindersAvailable: true,
      bossMonthlyReportAvailable: true,
      gstCalculationsEnabled: false,
      taxInvoiceWordingEnabled: false,
      moneyChangeAuditAvailable: true,
      paymentVoidAvailable: true,
      scrollableSidebarAvailable: true,
      usefulMissionRadarAvailable: true,
      radarPriorityLegendAvailable: true,
      radarActionButtonAvailable: true,
      dashboardCompressionAvailable: true,
      zeroStatePolishAvailable: true,
      missionControlUiRefinementAvailable: true,
      marcusTodayHeroPanelAvailable: true,
      leadHeatMeterAvailable: true,
      stickyTopCommandBarAvailable: true,
      compactSystemCoreAvailable: true,
      commandTimelineAvailable: true,
      emptyStatesPolished: true,
      microInteractionsAvailable: true,
      colourHierarchyRefined: true,
      missionControlUiIntegrated: true,
      julesUiIdeasAppliedByCodex: true,
      cockpitGlassmorphismThemeAvailable: true,
      radarGridBackgroundAvailable: true,
      mainActionQueueAvailable: true,
      clientFilesComingSoonOnly: false,
      mockClientFilesRemoved: true,
      fullPhoneNumbersShownInProtectedApp: true,
      v615FollowupPerformancePreserved: true,
      v615TestCleanupPreserved: true,
      followUpQueuePaginationAvailable: true,
      followUpButtonsFixed: true,
      testFollowUpsHiddenByDefault: true,
      liveTestFollowUpCleanupAvailable: true,
      testDataHiddenByDefault: true,
      cleanupDoesNotRunOnPageLoad: true,
      performanceDashboardLimitAvailable: true,
      uiPolishAvailable: true,
      missionControlUxFinalPolishAvailable: true,
      marcusTodayPanelAvailable: true,
      sidebarNavigationGrouped: true,
      topCommandBarAvailable: true,
      focusModeAvailable: true,
      cleanLeadCardsAvailable: true,
      emptyStatesAvailable: true,
      colourHierarchyAvailable: true,
      dashboardDebugClutterRemoved: true,
      clientFilesHiddenUntilRealStorage: false,
      clientFilesMockDataRemoved: true,
      nonGstModeAvailable: true,
      gstRegistered: false,
      missionControlUiAvailable: true,
      futuristicCockpitThemeAvailable: true,
      dashboardDeclutterAvailable: true,
      mainDashboardSystemClutterHidden: true,
      leadDisplayNameCleanerAvailable: true,
      liveTestLeadCleanupAvailable: true,
      inAppCleanupDryRunAvailable: true,
      hardDeleteNoTypingRequired: true,
      hideTestLeadsFromDashboardAvailable: true,
      priceGuideAutomationEnabled: false,
      priceGuideOnHold: true,
      specificWorksBrainAvailable: true,
      antiGenericReplyGateAvailable: true,
      inAppLiveCleanupAvailable: true,
      showHideTestLeadsFilterAvailable: true,
      generatedLeadDisplayCleanupAvailable: true,
      marcusFioCleanupProtectionAvailable: true,
      fionCleanupProtectionAvailable: true,
      premiumGoldCommandCentreThemeAvailable: true,
      largerReadableFontsAvailable: true,
      testLeadCleanupAvailable: true,
      testLeadCleanupDryRunAvailable: true,
      testLeadCleanupSoftDeleteDefault: true,
      humanLikeSalesBrainAvailable: true,
      contextTruthGateAvailable: true,
      singaporeRenovationMeaningBrainAvailable: true,
      naturalReplyComposerAvailable: true,
      safetyGovernorAvailable: true,
      replyQualityJudgeAvailable: true,
      overClaimPreventionAvailable: true,
      localRenovationShortformSupportAvailable: true,
      v6DeepQaAvailable: true,
      v6DeepQaCaseCount: 156,
      v6UltimateDeepQaAvailable: true,
      v6UltimateDeepQaCaseCount: 231,
      optionalAiSalesBrainAvailable: optionalAiSalesBrain.available,
      optionalAiSalesBrainEnabled: optionalAiSalesBrain.enabled,
      aiDraftReplyEnabled: optionalAiSalesBrain.draftReplyEnabled,
      aiJsonSchemaValidationAvailable: optionalAiSalesBrain.jsonSchemaValidationAvailable,
      deepWhatsappAgentQaAvailable: true,
      webhookPayloadSimulatorAvailable: true,
      mediaContextDetectionAvailable: true,
      floorPlanImageContextAvailable: true,
      avoidAskingForReceivedMediaAvailable: true,
      voiceMessageFallbackAvailable: true,
      voiceTranscriptionEnabled: false,
      singlishIntentSupportAvailable: true,
      singlishRepliesInEnglish: true,
      humanEscalationIntentAvailable: true,
      emailHandoffAvailable: handoffEmail.available,
      handoffEmailConfigured: handoffEmail.configured,
      handoffEmailToConfigured: handoffEmail.toConfigured,
      handoffEmailToDomain: handoffEmail.toDomain,
      handoffEmailProviderConfigured: handoffEmail.providerConfigured,
      handoffEmailAntiSpamAvailable: true,
      multiIntentDetectorAvailable: true,
      combinedReplyComposerAvailable: true,
      leadContextMemoryCheckerAvailable: true,
      avoidRepeatedInfoRequestAvailable: true,
      priceScopeFirstRuleAvailable: true,
      portfolioInstagramRoutingAvailable: true,
      instagramUrlConfigured,
      portfolioHumanFollowUpTaskAvailable: false,
      replyCoachAvailable: true,
      replyDecisionEngineAvailable: true,
      replyQualityGateAvailable: true,
      validTextNeverEmptyReplyGuard: true,
      noSilenceFallbackAvailable: true,
      safetyRewriteInsteadOfSilence: true,
      repetitionRewriteInsteadOfSilence: true,
      answerActualQuestionFirstRule: true,
      blackBoxReplyRecorderAvailable: true,
      humanTakeoverLockPlanned: true,
      softDeleteAvailable: true,
      restoreAvailable: true,
      bossOnlyHardDeleteAvailable: true,
      deleteAuditAvailable: true,
      humanTakeoverAvailable: true,
      botPauseResumeAvailable: true,
      leadScoringAvailable: true,
      conversationSummaryAvailable: true,
      missionQueueAvailable: true,
      followUpReminderAvailable: true,
      staffRolesAvailable: true,
      settingsPageAvailable: true,
      goldCommandCentreUiAvailable: true,
      inAppQaCentreAvailable: true,
      salesLearningFoundationAvailable: true,
      weeklyBossReportDraftAvailable: true,
      quotationReadinessAvailable: true,
      questionBankAvailable: true,
      questionBankCategories: questionBank.categories,
      questionBankExamples: questionBank.exampleQuestions,
      fallbackBrainAvailable: true,
      safetyValidatorAvailable: true,
      repetitionCheckerAvailable: true,
      hasSupabaseUrl: envPresent("NEXT_PUBLIC_SUPABASE_URL"),
      hasSupabaseAnonKey: envPresent("NEXT_PUBLIC_SUPABASE_ANON_KEY"),
      hasServiceRoleKey: envPresent("SUPABASE_SERVICE_ROLE_KEY"),
      liveInboundEnabled: envFlag("WHATSAPP_LIVE_INBOUND_ENABLED"),
      testAutoReplyEnabled: envFlag("WHATSAPP_TEST_AUTO_REPLY_ENABLED"),
      publicAutoReplyEnabled: envFlag("WHATSAPP_PUBLIC_AUTO_REPLY_ENABLED"),
      testMode: envFlag("WHATSAPP_TEST_MODE", true),
      hasWhatsappVerifyToken: envPresent("WHATSAPP_VERIFY_TOKEN"),
      hasWhatsappPhoneNumberId: envPresent("WHATSAPP_PHONE_NUMBER_ID"),
      hasWhatsappAccessToken: envPresent("WHATSAPP_ACCESS_TOKEN"),
      hasWhatsappBusinessNumber: envPresent("WHATSAPP_BUSINESS_NUMBER"),
      openaiWhatsappReplyEnabled: openAiWhatsApp.enabled,
      hasOpenaiApiKey: openAiWhatsApp.keyConfigured,
      whatsappReplyBrainDebug: openAiWhatsApp.debug,
      calendarBookingEnabled: calendar.bookingEnabled,
      calendarBossApprovalRequired: calendar.bossApprovalRequired,
      calendarAutoBookingEnabled: calendar.autoBookingEnabled,
      googleCalendarConnected: calendar.googleCalendarConnected,
      hasGoogleCalendarId: calendar.calendarIdConfigured,
      hasCalendarTimezone: calendar.hasCalendarTimezone
    });
  } catch {
    return NextResponse.json({
      ok: true,
      version: "v7_world_class_whatsapp_sales_brain",
      salesBrainVersion: "v7",
      runtime: "vercel",
      worldClassSalesConversationBrainAvailable: false,
      memoryFirstReplyComposerAvailable: false,
      knownInfoAcknowledgementBeforeQuestions: false,
      shortPingSmartReplyAvailable: false,
      confusionPingSmartReplyAvailable: false,
      alreadyToldYouRecoveryAvailable: false,
      budgetStatementNotPriceQuestionAvailable: false,
      contextAwareMissingInfoQuestionsAvailable: false,
      maxThreeQuestionsDefaultAvailable: false,
      genericFallbackReducedAvailable: false,
      conversationReplayTestAvailable: false,
      intakeKnownInfoAcknowledgementAvailable: false,
      budgetStatementClassificationAvailable: false,
      budgetExpectationNotPriceQuestionAvailable: false,
      intakeMissingInfoDeduplicationAvailable: false,
      addressExtractionAvailable: false,
      timelineExtractionAvailable: false,
      landedAaExtractionAvailable: false,
      finalSafetyFalsePositiveFixAvailable: false,
      safeFallbackFinalValidationAllowed: false,
      ultraSafeFallbackRewriteAvailable: false,
      finalValidationReasonLoggingAvailable: false,
      clientFileStorageAvailable: false,
      supabaseClientFilesBucketConfigured: false,
      leadFilesTableAvailable: false,
      whatsappMediaStorageAvailable: false,
      whatsappImageStorageAvailable: false,
      whatsappDocumentStorageAvailable: false,
      clientUploadLinkAvailable: false,
      secureUploadTokenAvailable: false,
      leadDetailFilePanelAvailable: false,
      clientFilesPageRealDataAvailable: false,
      signedFileUrlAvailable: false,
      fileCategoryDetectionAvailable: false,
      fileStatusTrackingAvailable: false,
      fileReviewWorkflowAvailable: false,
      fileVoidInsteadOfDeleteAvailable: false,
      fileUploadAuditAvailable: false,
      meetingReadinessFileConnectionAvailable: false,
      quotationReadinessFileConnectionAvailable: false,
      strategicCommandCoreAvailable: false,
      commandCoreBetaRouteAvailable: false,
      frostpunkInspiredLayoutAvailable: false,
      commandCoreFinalTouchupAvailable: false,
      commandCoreResourceBarContrastFixed: false,
      commandCoreOperatingPictureCompressed: false,
      commandCoreMapHeroPreserved: false,
      commandCoreBottomPanelsAligned: false,
      commandCoreMapFirstLayoutAvailable: false,
      commandCoreMapFullWidthHeroAvailable: false,
      commandCoreMapSameSizeAsDashboardAvailable: false,
      commandCoreResourceBarReadable: false,
      commandCorePaleResourceCardsRemoved: false,
      commandCoreSidePanelsNoLongerSqueezeMap: false,
      commandCoreWideMapLayoutAvailable: false,
      commandCoreMapDominantLayoutAvailable: false,
      commandCoreMapUsesFullPanelWidth: false,
      topResourceBarAvailable: false,
      marcusDecisionsPanelAvailable: false,
      rightInspectorPanelAvailable: false,
      bottomTimelineStripAvailable: false,
      commandCoreUsesRealDataOnly: false,
      currentDashboardPreserved: false,
      ui100CommandCentrePolishAvailable: false,
      dashboardBossActionClarityAvailable: false,
      marcusToday100PolishAvailable: false,
      leadCards100PolishAvailable: false,
      sidebar100PolishAvailable: false,
      followUpQueueUiPreserved: false,
      leadDetail100PolishAvailable: false,
      emptyStates100PolishAvailable: false,
      mobileUiPolishAvailable: false,
      interactionFeedbackPolishAvailable: false,
      performanceSafeUiPolishAvailable: false,
      officialSingaporeMapPreserved: false,
      mapDefaultZoomStartsAt100: false,
      mapSmoothZoomControlsAvailable: false,
      mapResetClearsPanSelectionTooltip: false,
      mapWheelZoomAvailable: false,
      mapWheelPreventsPageScroll: false,
      mapWheelListenerPassiveFalse: false,
      mapDefaultFitImproved: false,
      mapHorizontalSpaceOptimized: false,
      mapResetClearsSelection: false,
      mapFilterEmptyStatePolished: false,
      mapTopLeftCopyDeduped: false,
      mapHelperTextMovedToBottom: false,
      mapNoStackedStatusLabels: false,
      mapInspectorPanelAvailable: false,
      mapHqMarkerScalePolished: false,
      mapResetButtonFixed: false,
      mapResetRestoresDefaultFit: false,
      mapZoomControlsReliable: false,
      mapZoomBoundsAvailable: false,
      mapZoomPercentAccurate: false,
      mapPanDragAvailable: false,
      mapResetClearsPanAndSelection: false,
      mapAreaClickSummaryAvailable: false,
      mapPinClickSummaryAvailable: false,
      mapHqTooltipAvailable: false,
      mapAreaCountBubblesAvailable: false,
      mapFiltersAffectPinsAvailable: false,
      officialMapGeometryPreserved: false,
      officialSingaporePlanningAreaMapAvailable: false,
      mapFitToBoundsAvailable: false,
      mapCroppingFixed: false,
      areaLabelsBoundedToPolygons: false,
      hqMarkerCentralSingaporeAvailable: false,
      fakeSentosaRemoved: false,
      realSingaporeGeojsonMapAvailable: false,
      realMapGeometryAssetAvailable: false,
      manualBlobMapRemoved: false,
      hqMarkerPostal228397Available: false,
      googleMapsEnabled: false,
      realSingaporeOutlineAvailable: false,
      hqMarkerCentralSingaporeCalibrated: false,
      sentosaScaledShapeRefined: false,
      mapAreaLabelsAvailable: false,
      largeMapHelperBoxRemoved: false,
      smartLeadIntakeAvailable: false,
      meetingPrepBrainAvailable: false,
      lifestyleIntakeAvailable: false,
      householdOccupantsIntakeAvailable: false,
      helperPetsIntakeAvailable: false,
      safetyAccessibilityIntakeAvailable: false,
      budgetExpectationCaptureAvailable: false,
      timelineKeyMoveInCaptureAvailable: false,
      intakeChecklistAvailable: false,
      missingInfoDetectorAvailable: false,
      intakeQuestionLimitAvailable: false,
      maxFiveQuestionsRuleAvailable: false,
      noOverlyTechnicalFirstContactQuestions: false,
      intakeQuestionLimitMin: 0,
      intakeQuestionLimitMax: 0,
      lifestyleOccupantsPetsSafetyAvailable: false,
      budgetExpectationCollectionNoPriceReply: false,
      timelineKeyMoveInCollectionAvailable: false,
      meetingReadinessScoreAvailable: false,
      proposalReadinessScoreAvailable: false,
      leadIntakeProfileStorageAvailable: false,
      leadIntakeAuditTraceAvailable: false,
      accurateSingaporeSvgMapAvailable: false,
      singaporeMainlandSvgAvailable: false,
      sentosaOnlyIslandAvailable: false,
      singaporeMapWideLayoutAvailable: false,
      singaporeMapZoomableAvailable: false,
      singaporeMapPanAvailable: false,
      singaporeMapResetZoomAvailable: false,
      singaporeMapHqMarkerAvailable: false,
      singaporeMapHqPostalCode: "228397",
      singaporeMapSentosaOnlyAvailable: false,
      goldAmberColourSeparationFixed: false,
      accurateSingaporeMapAvailable: false,
      mapNoBlockingOverlayAvailable: false,
      mapBaseAlwaysVisible: false,
      subtleEmptyStateHelperAvailable: false,
      singaporeTacticalMapUiAvailable: false,
      singaporeSilhouetteMapAvailable: false,
      mapEmptyStatePolished: false,
      mapLegendIntegrated: false,
      mapAreaSummaryPanelAvailable: false,
      singaporeMissionMapAvailable: false,
      hybridAreaHeatmapAvailable: false,
      clickableMapPinsAvailable: false,
      mapAreaSummaryAvailable: false,
      mapFiltersAvailable: false,
      privacySafeMapDisplayAvailable: false,
      locationConfidenceAvailable: false,
      localSingaporeLocationParserAvailable: false,
      externalGeocodingEnabled: false,
      mapHidesTestDataByDefault: false,
      salesCollectionMapLayerAvailable: false,
      salesPipelineAvailable: false,
      manualQuotationTrackingAvailable: false,
      monthlySalesTargetsAvailable: false,
      monthlyCollectionTargetsAvailable: false,
      potentialQuotedConfirmedValuesAvailable: false,
      wonLostTrackingAvailable: false,
      leadToProjectConversionAvailable: false,
      paymentCollectionTrackerAvailable: false,
      outstandingReceivablesAvailable: false,
      overdueReceivablesAvailable: false,
      quotationPaymentFollowUpRemindersAvailable: false,
      bossMonthlyReportAvailable: false,
      gstCalculationsEnabled: false,
      taxInvoiceWordingEnabled: false,
      moneyChangeAuditAvailable: false,
      paymentVoidAvailable: false,
      scrollableSidebarAvailable: false,
      usefulMissionRadarAvailable: false,
      radarPriorityLegendAvailable: false,
      radarActionButtonAvailable: false,
      dashboardCompressionAvailable: false,
      zeroStatePolishAvailable: false,
      missionControlUiRefinementAvailable: false,
      marcusTodayHeroPanelAvailable: false,
      leadHeatMeterAvailable: false,
      stickyTopCommandBarAvailable: false,
      compactSystemCoreAvailable: false,
      commandTimelineAvailable: false,
      emptyStatesPolished: false,
      microInteractionsAvailable: false,
      colourHierarchyRefined: false,
      missionControlUiIntegrated: false,
      julesUiIdeasAppliedByCodex: false,
      cockpitGlassmorphismThemeAvailable: false,
      radarGridBackgroundAvailable: false,
      mainActionQueueAvailable: false,
      clientFilesComingSoonOnly: false,
      mockClientFilesRemoved: false,
      fullPhoneNumbersShownInProtectedApp: false,
      v615FollowupPerformancePreserved: false,
      v615TestCleanupPreserved: false,
      followUpQueuePaginationAvailable: false,
      followUpButtonsFixed: false,
      testFollowUpsHiddenByDefault: false,
      liveTestFollowUpCleanupAvailable: false,
      testDataHiddenByDefault: false,
      cleanupDoesNotRunOnPageLoad: false,
      performanceDashboardLimitAvailable: false,
      uiPolishAvailable: false,
      missionControlUxFinalPolishAvailable: false,
      marcusTodayPanelAvailable: false,
      sidebarNavigationGrouped: false,
      topCommandBarAvailable: false,
      focusModeAvailable: false,
      cleanLeadCardsAvailable: false,
      emptyStatesAvailable: false,
      colourHierarchyAvailable: false,
      dashboardDebugClutterRemoved: false,
      clientFilesHiddenUntilRealStorage: false,
      clientFilesMockDataRemoved: false,
      nonGstModeAvailable: true,
      gstRegistered: false,
      missionControlUiAvailable: false,
      futuristicCockpitThemeAvailable: false,
      dashboardDeclutterAvailable: false,
      mainDashboardSystemClutterHidden: false,
      leadDisplayNameCleanerAvailable: false,
      liveTestLeadCleanupAvailable: false,
      inAppCleanupDryRunAvailable: false,
      hardDeleteNoTypingRequired: false,
      hideTestLeadsFromDashboardAvailable: false,
      priceGuideAutomationEnabled: false,
      priceGuideOnHold: true,
      specificWorksBrainAvailable: false,
      antiGenericReplyGateAvailable: false,
      inAppLiveCleanupAvailable: false,
      showHideTestLeadsFilterAvailable: false,
      generatedLeadDisplayCleanupAvailable: false,
      marcusFioCleanupProtectionAvailable: false,
      fionCleanupProtectionAvailable: false,
      premiumGoldCommandCentreThemeAvailable: false,
      largerReadableFontsAvailable: false,
      testLeadCleanupAvailable: false,
      testLeadCleanupDryRunAvailable: false,
      testLeadCleanupSoftDeleteDefault: true,
      humanLikeSalesBrainAvailable: false,
      contextTruthGateAvailable: false,
      singaporeRenovationMeaningBrainAvailable: false,
      naturalReplyComposerAvailable: false,
      safetyGovernorAvailable: false,
      replyQualityJudgeAvailable: false,
      overClaimPreventionAvailable: false,
      localRenovationShortformSupportAvailable: false,
      v6DeepQaAvailable: false,
      v6DeepQaCaseCount: 0,
      v6UltimateDeepQaAvailable: false,
      v6UltimateDeepQaCaseCount: 0,
      optionalAiSalesBrainAvailable: true,
      optionalAiSalesBrainEnabled: false,
      aiDraftReplyEnabled: false,
      aiJsonSchemaValidationAvailable: false,
      deepWhatsappAgentQaAvailable: false,
      webhookPayloadSimulatorAvailable: false,
      mediaContextDetectionAvailable: false,
      floorPlanImageContextAvailable: false,
      avoidAskingForReceivedMediaAvailable: false,
      voiceMessageFallbackAvailable: false,
      voiceTranscriptionEnabled: false,
      singlishIntentSupportAvailable: false,
      singlishRepliesInEnglish: false,
      humanEscalationIntentAvailable: false,
      emailHandoffAvailable: true,
      handoffEmailConfigured: false,
      handoffEmailToConfigured: true,
      handoffEmailToDomain: "gmail.com",
      handoffEmailProviderConfigured: false,
      handoffEmailAntiSpamAvailable: false,
      multiIntentDetectorAvailable: false,
      combinedReplyComposerAvailable: false,
      leadContextMemoryCheckerAvailable: false,
      avoidRepeatedInfoRequestAvailable: false,
      priceScopeFirstRuleAvailable: false,
      portfolioInstagramRoutingAvailable: false,
      instagramUrlConfigured: false,
      portfolioHumanFollowUpTaskAvailable: false,
      replyCoachAvailable: false,
      replyDecisionEngineAvailable: false,
      replyQualityGateAvailable: false,
      validTextNeverEmptyReplyGuard: false,
      noSilenceFallbackAvailable: false,
      safetyRewriteInsteadOfSilence: false,
      repetitionRewriteInsteadOfSilence: false,
      answerActualQuestionFirstRule: false,
      blackBoxReplyRecorderAvailable: false,
      humanTakeoverLockPlanned: true,
      softDeleteAvailable: false,
      restoreAvailable: false,
      bossOnlyHardDeleteAvailable: false,
      deleteAuditAvailable: false,
      humanTakeoverAvailable: false,
      botPauseResumeAvailable: false,
      leadScoringAvailable: false,
      conversationSummaryAvailable: false,
      missionQueueAvailable: false,
      followUpReminderAvailable: false,
      staffRolesAvailable: false,
      settingsPageAvailable: false,
      goldCommandCentreUiAvailable: false,
      inAppQaCentreAvailable: false,
      salesLearningFoundationAvailable: false,
      weeklyBossReportDraftAvailable: false,
      quotationReadinessAvailable: false,
      questionBankAvailable: false,
      questionBankCategories: 0,
      questionBankExamples: 0,
      fallbackBrainAvailable: false,
      safetyValidatorAvailable: false,
      repetitionCheckerAvailable: false,
      hasSupabaseUrl: false,
      hasSupabaseAnonKey: false,
      hasServiceRoleKey: false,
      liveInboundEnabled: false,
      testAutoReplyEnabled: false,
      publicAutoReplyEnabled: false,
      testMode: false,
      hasWhatsappVerifyToken: false,
      hasWhatsappPhoneNumberId: false,
      hasWhatsappAccessToken: false,
      hasWhatsappBusinessNumber: false,
      openaiWhatsappReplyEnabled: false,
      hasOpenaiApiKey: false,
      whatsappReplyBrainDebug: false,
      calendarBookingEnabled: false,
      calendarBossApprovalRequired: true,
      calendarAutoBookingEnabled: false,
      googleCalendarConnected: false,
      hasGoogleCalendarId: false,
      hasCalendarTimezone: true
    });
  }
}
