import { NextResponse } from "next/server";
import { getCalendarRuntime } from "@/lib/calendar-config";
import { getHandoffEmailRuntime } from "@/lib/handoff-email";
import { getOpenAiWhatsAppReplyRuntime } from "@/lib/openai-whatsapp-config";
import { getOptionalAiSalesBrainRuntime } from "@/lib/whatsapp-v6/sales-brain";
import { getLimmInstagramUrl } from "@/lib/whatsapp-lead-context";
import { singaporeOfficialPlanningAreaMapAvailable } from "@/lib/singapore-map-geometry";
import { questionBankStats } from "@/lib/whatsapp-question-bank";
import { getClientFilesStorageRuntime } from "@/lib/data/lead-files-repository";
import { getWhatsAppConversationConcurrencyHealth } from "@/lib/data/whatsapp-conversation-lock-repository";
import { getSupabasePublicKey } from "@/lib/data/data-source";
import { hasSupabaseAdminEnv } from "@/lib/data/supabase-admin";
import { getWhatsAppProductionProofSnapshot } from "@/lib/data/whatsapp-webhook-failures-repository";
import { getWhatsAppQueueHealth } from "@/lib/data/whatsapp-inbound-jobs-repository";
import { getClientFileRecoverySnapshot } from "@/lib/data/client-file-recovery-repository";
import { getDatabaseRecoverySnapshot } from "@/lib/data/database-recovery-repository";
import { getReliabilityIncidentSnapshot } from "@/lib/data/reliability-incidents-repository";
import { getOperationsSloSnapshot } from "@/lib/operations/observability";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

// Version-history markers kept so older static phase checks can still verify the v6.3 layer:
// version: "v6_3_sales_collection_command_centre"
// salesBrainVersion: "v6.3"
// version: "v6_4_singapore_mission_map"
// salesBrainVersion: "v6.4"
// version: "v6_4_1_singapore_tactical_map_ui_polish"
// salesBrainVersion: "v6.4.1"
// version: "v6_4_2_accurate_singapore_map_no_overlay"
// salesBrainVersion: "v6.4.2"
// version: "v6_4_3_singapore_map_zoom_hq_redesign"
// salesBrainVersion: "v6.4.3"
// version: "v6_4_4_accurate_singapore_svg_map_fix"
// salesBrainVersion: "v6.4.4"
// version: "v6_4_5_real_singapore_geojson_map"
// salesBrainVersion: "v6.4.5"
// version: "v6_4_6_official_singapore_planning_area_map"
// salesBrainVersion: "v6.4.6"
// version: "v6_4_8_singapore_map_interaction_final_polish"
// salesBrainVersion: "v6.4.8"
// version: "v6_4_9_singapore_map_smooth_zoom_wheel_lock"
// salesBrainVersion: "v6.4.9"
// version: "v6_4_10_singapore_map_interaction_copy_cleanup"
// salesBrainVersion: "v6.4.10"
// version: "v6_5_smart_lead_intake_meeting_prep"
// salesBrainVersion: "v6.5"
// version: "v6_5_1_accurate_singapore_map_refinement"
// salesBrainVersion: "v6.5.1"
// version: "v6_ui_100_command_centre_polish"
// version: "v6_6_strategic_command_core_layout"
// version: "v6_6_1_strategic_command_core_ui_fit_polish"
// version: "v6_6_2_command_core_map_first_layout"
// version: "v6_6_3_strategic_command_core_final_touchup"
// version: "v6_7_real_client_file_upload_whatsapp_media_storage"
// salesBrainVersion: "v6.7"
// version: "v6_7_1_whatsapp_final_safety_false_positive_fix"
// salesBrainVersion: "v6.7.1"
// version: "v6_5_1_intake_memory_budget_statement_fix"
// version: "v7_world_class_whatsapp_sales_brain"
// salesBrainVersion: "v7"
// version: "v7_1_whatsapp_conversation_memory_contract_fix"
// salesBrainVersion: "v7.1"
// version: "v7_2_single_reply_planner_playbook_v5"
// salesBrainVersion: "v7.2"
// version: "v7_2_1_context_aware_next_item_client_name_rule"
// salesBrainVersion: "v7.2.1"
// version: "v7_2_2_price_reply_uses_known_context"
// salesBrainVersion: "v7.2.2"
// version: "v7_2_3_remove_legacy_whatsapp_reply_templates"
// salesBrainVersion: "v7.2.3"
// version: "v8_0_sales_agent_reliability_replay_system"
// salesBrainVersion: "v8.0"
// version: "v9_0_clean_whatsapp_sales_brain"
// salesBrainVersion: "v9_clean_core"
// version: "v10_boss_operations_command_centre_pwa"
// version: "v10_2_0_intent_gate_conversation_safety"
// salesBrainVersion: "v10.2.0"
// version: "v10_2_1_conversation_concurrency_safety"
// salesBrainVersion: "v10.2.1"
// version: "v10_2_2_webhook_auth_dependency_hardening"
// securityVersion: "v10.2.2"
// version: "v10_2_3_inbox_latest_activity_spam_cleanup"
// uiVersion: "v10.2.3"
// version: "v10_3_0_inbox_operator_experience"
// uiVersion: "v10.3.0"
// version: "v10_4_0_command_centre_product_polish"
// uiVersion: "v10.4.0"
// version: "v10_5_0_command_centre_10_quality"
// uiVersion: "v10.5.0"
// version: "v10_6_0_operator_advantage"
// uiVersion: "v10.6.0"
// version: "v11_1_0_world_class_operations"
// uiVersion: "v11.1.0"
// version: "v11_1_3_outbound_hotfix"
// uiVersion: "v11.1.3"
// version: "v11_3_0_reliability_disaster_recovery"
// reliabilityVersion: "v11.3.0"
// version: "v11_4_0_recovery_readiness"
// reliabilityVersion: "v11.4.0"

function envPresent(name: string) {
  return Boolean(process.env[name]);
}

function envFlag(name: string, fallback = false) {
  const value = process.env[name];
  if (value === undefined || value === "") return fallback;
  return value.toLowerCase() === "true";
}

export async function GET() {
  try {
    const openAiWhatsApp = getOpenAiWhatsAppReplyRuntime();
    const optionalAiSalesBrain = getOptionalAiSalesBrainRuntime();
    const calendar = getCalendarRuntime();
    const handoffEmail = getHandoffEmailRuntime();
    const questionBank = questionBankStats();
    const instagramUrlConfigured = Boolean(getLimmInstagramUrl());
    const clientFilesStorage = getClientFilesStorageRuntime();
    const officialSingaporePlanningAreaMapAvailable = singaporeOfficialPlanningAreaMapAvailable();
    const [concurrencySafety, operations, whatsappProof, queueReliability, fileRecovery, databaseRecovery, reliabilityIncidents] = await Promise.all([
      getWhatsAppConversationConcurrencyHealth(),
      getOperationsSloSnapshot(),
      getWhatsAppProductionProofSnapshot(),
      getWhatsAppQueueHealth(),
      getClientFileRecoverySnapshot(),
      getDatabaseRecoverySnapshot(),
      getReliabilityIncidentSnapshot()
    ]);
    const webhookSignatureEnforced = envPresent("WHATSAPP_APP_SECRET");
    const concurrencySafetyReady =
      concurrencySafety.databaseConnected &&
      concurrencySafety.migration027Ready &&
      concurrencySafety.migration028Ready &&
      concurrencySafety.migration031Ready;
    const whatsappProductionSafetyReady = concurrencySafetyReady && webhookSignatureEnforced;
    return NextResponse.json({
      ok: true,
      version: "v11_4_0_recovery_readiness",
      salesBrainVersion: "v10.2.1",
      securityVersion: "v10.2.2",
      uiVersion: "v11.4.0",
      reliabilityVersion: "v11.4.0",
      underlyingSalesComposerVersion: "v9_clean_core",
      runtime: "vercel",
      webhookSignatureVerificationAvailable: true,
      webhookSignatureEnforced,
      crossInstanceConversationLeaseAvailable: concurrencySafety.migration028Ready,
      atomicReplyReservationAvailable: concurrencySafety.migration028Ready,
      finalPreSendContextRefreshAvailable: true,
      newerInboundStaleReplySuppressionAvailable: true,
      inboundBurstSettleAvailable: true,
      historicalDuplicateDisplayCollapseAvailable: true,
      legacyIntentClassificationLabelsAvailable: true,
      leadFactsInboundEvidenceOnly: true,
      databaseConnected: concurrencySafety.databaseConnected,
      migration027Ready: concurrencySafety.migration027Ready,
      migration028Ready: concurrencySafety.migration028Ready,
      migration031Ready: concurrencySafety.migration031Ready,
      intakeProfileSchemaReady: concurrencySafety.intakeProfileReady,
      inboundFailureRecoveryAvailable: concurrencySafety.failureRecoveryReady,
      schemaCompatibilityRetryAvailable: true,
      productionSchemaDeploymentGateAvailable: true,
      bossOnlyFailureRecoveryWorkspaceAvailable: true,
      noSendFailureRecoveryAvailable: true,
      authenticatedQaReleaseGateAvailable: true,
      trustedWebhookLeadControlReadAvailable: true,
      unexpectedNoSendTelemetryAvailable: true,
      outboundTerminalProofRequired: true,
      durableInboundQueueAvailable: queueReliability.available,
      durableInboundQueuedCount: queueReliability.queuedCount,
      durableInboundProcessingCount: queueReliability.processingCount,
      durableInboundDeadLetterCount: queueReliability.deadLetterCount,
      durableInboundStaleLeaseCount: queueReliability.staleProcessingCount,
      durableInboundCompletedLast24hCount: queueReliability.completedLast24hCount,
      durableInboundRetryScheduledLast24hCount: queueReliability.retryScheduledLast24hCount,
      durableWorkerLastSucceededAt: queueReliability.workerLastSucceededAt,
      durableWorkerStatus: queueReliability.workerStatus,
      expiredProcessingLeaseRecoveryAvailable: true,
      minuteLevelSupabaseCronRecoveryAvailable: Boolean(queueReliability.workerLastSucceededAt),
      durableAttemptHistoryAvailable: queueReliability.available,
      bossDeadLetterReplayAvailable: true,
      clientFileIntegrityControlAvailable: fileRecovery.available,
      clientFileLatestIntegrityAt: fileRecovery.latestIntegrityAt,
      clientFileLatestIntegrityStatus: fileRecovery.latestIntegrityStatus,
      clientFileOffsiteBackupConfigured: fileRecovery.offsiteConfigured,
      clientFileLatestBackupAt: fileRecovery.latestBackupAt,
      clientFileLatestBackupStatus: fileRecovery.latestBackupStatus,
      clientFileProtectedObjectCount: fileRecovery.protectedObjectCount,
      clientFileRestoreBucketIsolated: fileRecovery.restoreBucketIsolated,
      clientFileLatestRestoreDrillAt: fileRecovery.latestRestoreDrillAt,
      clientFileLatestRestoreDrillStatus: fileRecovery.latestRestoreDrillStatus,
      clientFileBackupDailyManifestRetention: 35,
      clientFileBackupMonthlyManifestRetention: 12,
      clientFileDisasterRecoveryReady:
        fileRecovery.offsiteConfigured &&
        fileRecovery.latestBackupStatus === "succeeded" &&
        fileRecovery.restoreBucketIsolated &&
        fileRecovery.latestRestoreDrillStatus === "succeeded",
      reliabilityIncidentLedgerAvailable: reliabilityIncidents.available,
      reliabilityWatchdogLastSucceededAt: reliabilityIncidents.watchdogLastSucceededAt,
      reliabilityWatchdogStatus: reliabilityIncidents.watchdogStatus,
      reliabilityOpenCriticalIncidentCount: reliabilityIncidents.openCriticalCount,
      reliabilityOpenWarningIncidentCount: reliabilityIncidents.openWarningCount,
      reliabilityAcknowledgedIncidentCount: reliabilityIncidents.acknowledgedCount,
      reliabilityAlertsEnabled: reliabilityIncidents.alertEnabled,
      reliabilityAlertProviderConfigured: reliabilityIncidents.alertProviderConfigured,
      reliabilityAlertRecipientsConfigured: reliabilityIncidents.alertRecipientsConfigured,
      databaseRecoveryEvidenceAvailable: databaseRecovery.available,
      databaseRecoveryEvidenceReporterConfigured: databaseRecovery.evidenceReporterConfigured,
      databaseBackupConfigured: databaseRecovery.backupConfigured,
      databaseLatestBackupAt: databaseRecovery.latestBackupAt,
      databaseLatestBackupStatus: databaseRecovery.latestBackupStatus,
      databaseLatestBackupArtifactVerified: databaseRecovery.latestBackupArtifactVerified,
      databaseLatestBackupScope: databaseRecovery.latestBackupScope,
      databaseLatestBackupScopeComplete: databaseRecovery.latestBackupScopeComplete,
      databaseLatestRestoreDrillAt: databaseRecovery.latestRestoreDrillAt,
      databaseLatestRestoreDrillStatus: databaseRecovery.latestRestoreDrillStatus,
      databaseLatestRestoreIsolated: databaseRecovery.latestRestoreIsolated,
      databaseLatestRestoreMatchesBackup: databaseRecovery.latestRestoreMatchesBackup,
      databaseCoreBusinessDataRecoveryProven: databaseRecovery.coreBusinessDataRecoveryProven,
      databaseRecoveryUnresolvedRisk: databaseRecovery.unresolvedRisk,
      databaseBackupRpoHours: databaseRecovery.rpoHours,
      databaseRestoreRtoHours: databaseRecovery.rtoHours,
      databaseDisasterRecoveryReady: databaseRecovery.ready,
      recoveryReadinessReady:
        queueReliability.available &&
        queueReliability.deadLetterCount === 0 &&
        queueReliability.staleProcessingCount === 0 &&
        fileRecovery.offsiteConfigured &&
        fileRecovery.latestBackupStatus === "succeeded" &&
        fileRecovery.restoreBucketIsolated &&
        fileRecovery.latestRestoreDrillStatus === "succeeded" &&
        databaseRecovery.ready &&
        reliabilityIncidents.available &&
        reliabilityIncidents.openCriticalCount === 0,
      whatsappRecoveryProofSchemaReady: whatsappProof.schemaReady,
      unresolvedPreservedInboundCount: whatsappProof.pendingFailureCount,
      recoveredInboundLast24hCount: whatsappProof.recoveredLast24hCount,
      lastPreservedInboundFailureAt: whatsappProof.lastFailureAt,
      lastPreservedInboundRecoveryAt: whatsappProof.lastRecoveryAt,
      freshV1112RealInboundProofObserved: Boolean(whatsappProof.lastV1112InboundAt),
      freshV1112RealInboundProofAt: whatsappProof.lastV1112InboundAt,
      freshV1113RealInboundProofObserved: Boolean(whatsappProof.lastReleaseInboundAt),
      freshV1113RealInboundProofAt: whatsappProof.lastReleaseInboundAt,
      freshV1113RealOutboundProofObserved: Boolean(whatsappProof.lastReleaseOutboundAt),
      freshV1113RealOutboundProofAt: whatsappProof.lastReleaseOutboundAt,
      whatsappProductionSafetyReady,
      whatsappProductionSafetyReason: !concurrencySafetyReady
        ? concurrencySafety.reason
        : webhookSignatureEnforced
          ? "ready"
          : "webhook_app_secret_missing",
      intentGateAvailable: true,
      leadEligibilityGateAvailable: true,
      nonSalesRoutingAvailable: true,
      oneTimeVendorAcknowledgementAvailable: true,
      latestUnansweredQuestionAvailable: true,
      semanticDuplicateGuardAvailable: true,
      semanticDuplicateThreshold: 0.85,
      semanticDuplicateReplyWindow: 5,
      humanTakeoverFinalGuardAvailable: true,
      nonSalesSalesSurfaceExclusionAvailable: true,
      rawInboundBeforeIntentClassificationAvailable: true,
      intentGateAuditAvailable: true,
      manualIntentOverrideAvailable: true,
      classifierFailureSafeSuppressionAvailable: true,
      deterministicIntentBudgetMs: 100,
      intentContextMessageLimit: 10,
      v9ProductionRouteEnabled: true,
      legacyReplyLogicQuarantined: true,
      singleReplyCoreOnly: true,
      manualWhatsappOutboundReplyAvailable: true,
      inboxLatestActivityFirstAvailable: true,
      inboxQuickSpamRemovalAvailable: true,
      inboxQuickSpamRemovalRecoverable: true,
      inboxStickyComposerAvailable: true,
      inboxDetailsDrawerAvailable: true,
      inboxBulkSpamRemovalAvailable: true,
      inboxMobileQueueChatFlowAvailable: true,
      inboxTabletFullWidthAvailable: true,
      commandCentreUnifiedVisualSystemAvailable: true,
      commandCentreCompactResponsiveShellAvailable: true,
      commandCentreMobileIconNavigationAvailable: true,
      commandCentreRouteLoadingErrorStatesAvailable: true,
      commandCentreReducedMotionAvailable: true,
      inboxKeyboardShortcutsAvailable: true,
      inboxRememberedFilterAvailable: true,
      inboxAccessibleDetailsFocusTrapAvailable: true,
      commandCentreGlobalCommandPaletteAvailable: true,
      operatorPriorityCockpitAvailable: true,
      operatorContextActionPaletteAvailable: true,
      operatorConversationBriefAvailable: true,
      operatorResponseTargetMinutes: 60,
      operatorSavedInboxViewsAvailable: true,
      operatorSpamUndoAvailable: true,
      operatorQueueSyncHealthAvailable: true,
      operatorInboxInitialBundleBudgetKb: 140,
      privateRealtimeBroadcastAvailable: true,
      realtimePresenceAvailable: true,
      realtimePollingFallbackAvailable: true,
      atomicInboxAssignmentAvailable: true,
      personalAndTeamQueuesAvailable: true,
      internalTeamNotesAvailable: true,
      conversationCollisionWarningAvailable: true,
      realtimePwaAlertsAvailable: true,
      cursorInboxPaginationAvailable: true,
      virtualizedConversationRowsAvailable: true,
      operatorProductAnalyticsAvailable: true,
      distributedRateLimitAvailable: true,
      structuredOperationalTracesAvailable: true,
      productionSloDashboardAvailable: true,
      noSendSyntheticCanaryAvailable: true,
      securityHeadersAndCspAvailable: true,
      modernSupabaseKeyCompatibilityAvailable: true,
      versionedAiQualityObservationsAvailable: true,
      shadowReplyQualityEvaluationAvailable: true,
      operatorAiOutcomeFeedbackAvailable: true,
      aiQualityReleaseGateAvailable: true,
      revenueIntelligenceAvailable: true,
      responseTimeImpactAvailable: true,
      weightedRevenueForecastAvailable: true,
      revenuePriorityQueueAvailable: true,
      worldClassOperationsSchemaReady: operations.schemaReady,
      operations24hSuccessRatePercent: operations.successRatePercent,
      operations24hP95DurationMs: operations.p95DurationMs,
      commandCentreSkipNavigationAvailable: true,
      commandCentreSemanticHeadingHierarchyAvailable: true,
      commandCoreDeferredMapBundleAvailable: true,
      commandCoreInitialBundleBudgetKb: 120,
      commandCentreCrossRouteAccessibilityGateAvailable: true,
      commandCentreUnauthenticatedAccessibilityAvailable: true,
      duplicatePrioritySignalsSuppressedAvailable: true,
      collectionQueueOverflowContainedAvailable: true,
      bossDailyBriefAvailable: true,
      bossOpsNavigationGroupsAvailable: true,
      riskBadgesAvailable: true,
      bossReviewGateAvailable: true,
      quoteSentBossApprovalGateAvailable: true,
      doNotStartGateAvailable: true,
      collectionQueueAvailable: true,
      jbcDefaultPaymentScheduleAvailable: true,
      limmCustomMilestoneScheduleAvailable: true,
      singaporeTimezoneDateSafetyAvailable: true,
      pwaManifestAvailable: true,
      pwaServiceWorkerAvailable: true,
      pwaStandaloneDisplayAvailable: true,
      mobileBottomNavigationAvailable: true,
      cameraPhotoUploadSupportAvailable: true,
      leadConversationTimelineAvailable: true,
      manualTakeoverOnReplyAvailable: true,
      whatsappManualTestSendAvailable: true,
      replaySafeManualReplyPostRedirect: true,
      durableCorrectionMemoryAvailable: true,
      frustrationHandoffLockAvailable: true,
      hypotheticalContextSwitchGuardAvailable: true,
      antiRepeatGuardAvailable: true,
      singleReplyPlannerEnforced: true,
      goldenReplayPackAvailable: true,
      goldenReplayPackCount: 100,
      replayRunnerAvailable: true,
      replayVariationGeneratorAvailable: true,
      memoryBasedReplayAvailable: true,
      publicAutoReplyRecommended: false,
      legacyReplyTemplatesRemovedFromLivePath: true,
      replySourceTraceAvailable: true,
      legacyTemplateBlockedInFinalReplies: true,
      priceReplyUsesV72PlannerOnly: true,
      priceReplyNoScopeAskForSeriousAa: true,
      contextAwareNextUsefulItemAvailable: true,
      priceReplyUsesKnownContext: true,
      priceReplyNoBroadScopeAskForSeriousLandedAa: true,
      priceReplyDoesNotAskReceivedFiles: true,
      portfolioReplyUsesFileContext: true,
      priceReplyUsesKnownProjectContext: true,
      greetingKnownContextNatural: true,
      clientNameRuleAvailable: true,
      reviewReadyStopAskingRefinementAvailable: true,
      receivedFilesNotAskedAgain: true,
      seriousLandedAaNoBroadScopeAsk: true,
      playbookV5SingleReplyPlannerAvailable: true,
      salesMomentClassifierAvailable: true,
      clientPatienceDetectorAvailable: true,
      leadSeriousnessScorerAvailable: true,
      nextBestMoveSelectorAvailable: true,
      humanFeelJudgeAvailable: true,
      stopAskingRuleAvailable: true,
      seriousLandedAaRuleAvailable: true,
      questionBudgetByClientStateAvailable: true,
      directQuestionFirstEnforced: true,
      fileConfidenceStatusAvailable: true,
      clientFacingPlaceholderSuppressionAvailable: true,
      mergedLeadContextContractAvailable: true,
      clientFacingKnownSummaryBuilderAvailable: true,
      fileStatusQuestionIntentAvailable: true,
      floorplanStatusReplyAvailable: true,
      knownContextPersistenceAcrossReplies: true,
      shortPingUsesKnownContextAvailable: true,
      internalPlaceholderNeverClientFacing: true,
      worldClassSalesConversationBrainAvailable: true,
      memoryFirstReplyComposerAvailable: true,
      knownInfoAcknowledgementBeforeQuestions: true,
      shortPingSmartReplyAvailable: true,
      confusionPingSmartReplyAvailable: true,
      alreadyToldYouRecoveryAvailable: true,
      budgetStatementNotPriceQuestionAvailable: true,
      contextAwareMissingInfoQuestionsAvailable: true,
      maxThreeQuestionsDefaultAvailable: true,
      genericFallbackReducedAvailable: true,
      conversationReplayTestAvailable: true,
      intakeKnownInfoAcknowledgementAvailable: true,
      budgetStatementClassificationAvailable: true,
      budgetExpectationNotPriceQuestionAvailable: true,
      intakeMissingInfoDeduplicationAvailable: true,
      addressExtractionAvailable: true,
      timelineExtractionAvailable: true,
      landedAaExtractionAvailable: true,
      finalSafetyFalsePositiveFixAvailable: true,
      safeFallbackFinalValidationAllowed: true,
      ultraSafeFallbackRewriteAvailable: true,
      finalValidationReasonLoggingAvailable: true,
      clientFileStorageAvailable: true,
      supabaseClientFilesBucketConfigured: Boolean(clientFilesStorage.bucketName),
      leadFilesTableAvailable: true,
      whatsappMediaStorageAvailable: true,
      whatsappImageStorageAvailable: true,
      whatsappDocumentStorageAvailable: true,
      inboxMediaAttachmentVisibilityAvailable: true,
      privateInboxAttachmentRedirectAvailable: true,
      whatsappMediaFetchRetryAvailable: true,
      whatsappMediaManualRecoveryAvailable: true,
      whatsappAttachmentRealtimeRefreshAvailable: true,
      clientUploadLinkAvailable: true,
      secureUploadTokenAvailable: true,
      leadDetailFilePanelAvailable: true,
      clientFilesPageRealDataAvailable: true,
      signedFileUrlAvailable: true,
      fileCategoryDetectionAvailable: true,
      fileStatusTrackingAvailable: true,
      fileReviewWorkflowAvailable: true,
      fileVoidInsteadOfDeleteAvailable: true,
      fileUploadAuditAvailable: true,
      meetingReadinessFileConnectionAvailable: true,
      quotationReadinessFileConnectionAvailable: true,
      strategicCommandCoreAvailable: true,
      commandCoreBetaRouteAvailable: true,
      frostpunkInspiredLayoutAvailable: true,
      commandCoreFinalTouchupAvailable: true,
      commandCoreResourceBarContrastFixed: true,
      commandCoreOperatingPictureCompressed: true,
      commandCoreMapHeroPreserved: true,
      commandCoreBottomPanelsAligned: true,
      commandCoreMapFirstLayoutAvailable: true,
      commandCoreMapFullWidthHeroAvailable: true,
      commandCoreMapSameSizeAsDashboardAvailable: true,
      commandCoreResourceBarReadable: true,
      commandCorePaleResourceCardsRemoved: true,
      commandCoreSidePanelsNoLongerSqueezeMap: true,
      commandCoreWideMapLayoutAvailable: true,
      commandCoreMapDominantLayoutAvailable: true,
      commandCoreMapUsesFullPanelWidth: true,
      topResourceBarAvailable: true,
      marcusDecisionsPanelAvailable: true,
      rightInspectorPanelAvailable: true,
      bottomTimelineStripAvailable: true,
      commandCoreUsesRealDataOnly: true,
      currentDashboardPreserved: true,
      ui100CommandCentrePolishAvailable: true,
      dashboardBossActionClarityAvailable: true,
      marcusToday100PolishAvailable: true,
      leadCards100PolishAvailable: true,
      sidebar100PolishAvailable: true,
      followUpQueueUiPreserved: true,
      leadDetail100PolishAvailable: true,
      emptyStates100PolishAvailable: true,
      mobileUiPolishAvailable: true,
      interactionFeedbackPolishAvailable: true,
      performanceSafeUiPolishAvailable: true,
      officialSingaporeMapPreserved: true,
      mapDefaultZoomStartsAt100: true,
      mapSmoothZoomControlsAvailable: true,
      mapResetClearsPanSelectionTooltip: true,
      mapWheelZoomAvailable: true,
      mapWheelPreventsPageScroll: true,
      mapWheelListenerPassiveFalse: true,
      mapDefaultFitImproved: true,
      mapHorizontalSpaceOptimized: true,
      mapResetClearsSelection: true,
      mapFilterEmptyStatePolished: true,
      mapTopLeftCopyDeduped: true,
      mapHelperTextMovedToBottom: true,
      mapNoStackedStatusLabels: true,
      mapInspectorPanelAvailable: true,
      mapHqMarkerScalePolished: true,
      mapResetButtonFixed: true,
      mapResetRestoresDefaultFit: true,
      mapZoomControlsReliable: true,
      mapZoomBoundsAvailable: true,
      mapZoomPercentAccurate: true,
      mapPanDragAvailable: true,
      mapResetClearsPanAndSelection: true,
      mapAreaClickSummaryAvailable: true,
      mapPinClickSummaryAvailable: true,
      mapHqTooltipAvailable: true,
      mapAreaCountBubblesAvailable: true,
      mapFiltersAffectPinsAvailable: true,
      officialMapGeometryPreserved: true,
      officialSingaporePlanningAreaMapAvailable,
      mapFitToBoundsAvailable: true,
      mapCroppingFixed: true,
      areaLabelsBoundedToPolygons: true,
      hqMarkerCentralSingaporeAvailable: true,
      fakeSentosaRemoved: true,
      realSingaporeGeojsonMapAvailable: true,
      realMapGeometryAssetAvailable: true,
      manualBlobMapRemoved: true,
      hqMarkerPostal228397Available: true,
      googleMapsEnabled: false,
      realSingaporeOutlineAvailable: true,
      hqMarkerCentralSingaporeCalibrated: true,
      sentosaScaledShapeRefined: false,
      mapAreaLabelsAvailable: true,
      largeMapHelperBoxRemoved: true,
      smartLeadIntakeAvailable: true,
      meetingPrepBrainAvailable: true,
      lifestyleIntakeAvailable: true,
      householdOccupantsIntakeAvailable: true,
      helperPetsIntakeAvailable: true,
      safetyAccessibilityIntakeAvailable: true,
      budgetExpectationCaptureAvailable: true,
      timelineKeyMoveInCaptureAvailable: true,
      intakeChecklistAvailable: true,
      missingInfoDetectorAvailable: true,
      intakeQuestionLimitAvailable: true,
      maxFiveQuestionsRuleAvailable: true,
      noOverlyTechnicalFirstContactQuestions: true,
      intakeQuestionLimitMin: 3,
      intakeQuestionLimitMax: 5,
      lifestyleOccupantsPetsSafetyAvailable: true,
      budgetExpectationCollectionNoPriceReply: true,
      timelineKeyMoveInCollectionAvailable: true,
      meetingReadinessScoreAvailable: true,
      proposalReadinessScoreAvailable: true,
      leadIntakeProfileStorageAvailable: true,
      leadIntakeAuditTraceAvailable: true,
      accurateSingaporeSvgMapAvailable: true,
      singaporeMainlandSvgAvailable: true,
      sentosaOnlyIslandAvailable: false,
      singaporeMapWideLayoutAvailable: true,
      singaporeMapZoomableAvailable: true,
      singaporeMapPanAvailable: true,
      singaporeMapResetZoomAvailable: true,
      singaporeMapHqMarkerAvailable: true,
      singaporeMapHqPostalCode: "228397",
      singaporeMapSentosaOnlyAvailable: false,
      goldAmberColourSeparationFixed: true,
      accurateSingaporeMapAvailable: true,
      mapNoBlockingOverlayAvailable: true,
      mapBaseAlwaysVisible: true,
      subtleEmptyStateHelperAvailable: true,
      singaporeTacticalMapUiAvailable: true,
      singaporeSilhouetteMapAvailable: true,
      mapEmptyStatePolished: true,
      mapLegendIntegrated: true,
      mapAreaSummaryPanelAvailable: true,
      singaporeMissionMapAvailable: true,
      hybridAreaHeatmapAvailable: true,
      clickableMapPinsAvailable: true,
      mapAreaSummaryAvailable: true,
      mapFiltersAvailable: true,
      privacySafeMapDisplayAvailable: true,
      locationConfidenceAvailable: true,
      localSingaporeLocationParserAvailable: true,
      externalGeocodingEnabled: false,
      mapHidesTestDataByDefault: true,
      salesCollectionMapLayerAvailable: true,
      salesPipelineAvailable: true,
      manualQuotationTrackingAvailable: true,
      monthlySalesTargetsAvailable: true,
      monthlyCollectionTargetsAvailable: true,
      potentialQuotedConfirmedValuesAvailable: true,
      wonLostTrackingAvailable: true,
      leadToProjectConversionAvailable: true,
      paymentCollectionTrackerAvailable: true,
      outstandingReceivablesAvailable: true,
      overdueReceivablesAvailable: true,
      quotationPaymentFollowUpRemindersAvailable: true,
      bossMonthlyReportAvailable: true,
      gstCalculationsEnabled: false,
      taxInvoiceWordingEnabled: false,
      moneyChangeAuditAvailable: true,
      paymentVoidAvailable: true,
      scrollableSidebarAvailable: true,
      usefulMissionRadarAvailable: true,
      radarPriorityLegendAvailable: true,
      radarActionButtonAvailable: true,
      dashboardCompressionAvailable: true,
      zeroStatePolishAvailable: true,
      missionControlUiRefinementAvailable: true,
      marcusTodayHeroPanelAvailable: true,
      leadHeatMeterAvailable: true,
      stickyTopCommandBarAvailable: true,
      compactSystemCoreAvailable: true,
      commandTimelineAvailable: true,
      emptyStatesPolished: true,
      microInteractionsAvailable: true,
      colourHierarchyRefined: true,
      missionControlUiIntegrated: true,
      julesUiIdeasAppliedByCodex: true,
      cockpitGlassmorphismThemeAvailable: true,
      radarGridBackgroundAvailable: true,
      mainActionQueueAvailable: true,
      clientFilesComingSoonOnly: false,
      mockClientFilesRemoved: true,
      fullPhoneNumbersShownInProtectedApp: true,
      v615FollowupPerformancePreserved: true,
      v615TestCleanupPreserved: true,
      followUpQueuePaginationAvailable: true,
      followUpButtonsFixed: true,
      testFollowUpsHiddenByDefault: true,
      liveTestFollowUpCleanupAvailable: true,
      testDataHiddenByDefault: true,
      cleanupDoesNotRunOnPageLoad: true,
      performanceDashboardLimitAvailable: true,
      uiPolishAvailable: true,
      missionControlUxFinalPolishAvailable: true,
      marcusTodayPanelAvailable: true,
      sidebarNavigationGrouped: true,
      topCommandBarAvailable: true,
      focusModeAvailable: true,
      cleanLeadCardsAvailable: true,
      emptyStatesAvailable: true,
      colourHierarchyAvailable: true,
      dashboardDebugClutterRemoved: true,
      clientFilesHiddenUntilRealStorage: false,
      clientFilesMockDataRemoved: true,
      nonGstModeAvailable: true,
      gstRegistered: false,
      missionControlUiAvailable: true,
      futuristicCockpitThemeAvailable: true,
      dashboardDeclutterAvailable: true,
      mainDashboardSystemClutterHidden: true,
      leadDisplayNameCleanerAvailable: true,
      liveTestLeadCleanupAvailable: true,
      inAppCleanupDryRunAvailable: true,
      hardDeleteNoTypingRequired: true,
      hideTestLeadsFromDashboardAvailable: true,
      priceGuideAutomationEnabled: false,
      priceGuideOnHold: true,
      specificWorksBrainAvailable: true,
      antiGenericReplyGateAvailable: true,
      inAppLiveCleanupAvailable: true,
      showHideTestLeadsFilterAvailable: true,
      generatedLeadDisplayCleanupAvailable: true,
      marcusFioCleanupProtectionAvailable: true,
      fionCleanupProtectionAvailable: true,
      premiumGoldCommandCentreThemeAvailable: true,
      largerReadableFontsAvailable: true,
      testLeadCleanupAvailable: true,
      testLeadCleanupDryRunAvailable: true,
      testLeadCleanupSoftDeleteDefault: true,
      humanLikeSalesBrainAvailable: true,
      contextTruthGateAvailable: true,
      singaporeRenovationMeaningBrainAvailable: true,
      naturalReplyComposerAvailable: true,
      safetyGovernorAvailable: true,
      replyQualityJudgeAvailable: true,
      overClaimPreventionAvailable: true,
      localRenovationShortformSupportAvailable: true,
      v6DeepQaAvailable: true,
      v6DeepQaCaseCount: 156,
      v6UltimateDeepQaAvailable: true,
      v6UltimateDeepQaCaseCount: 231,
      optionalAiSalesBrainAvailable: optionalAiSalesBrain.available,
      optionalAiSalesBrainEnabled: optionalAiSalesBrain.enabled,
      aiDraftReplyEnabled: optionalAiSalesBrain.draftReplyEnabled,
      aiJsonSchemaValidationAvailable: optionalAiSalesBrain.jsonSchemaValidationAvailable,
      deepWhatsappAgentQaAvailable: true,
      webhookPayloadSimulatorAvailable: true,
      mediaContextDetectionAvailable: true,
      floorPlanImageContextAvailable: true,
      avoidAskingForReceivedMediaAvailable: true,
      voiceMessageFallbackAvailable: true,
      voiceTranscriptionEnabled: false,
      singlishIntentSupportAvailable: true,
      singlishRepliesInEnglish: true,
      humanEscalationIntentAvailable: true,
      emailHandoffAvailable: handoffEmail.available,
      handoffEmailConfigured: handoffEmail.configured,
      handoffEmailToConfigured: handoffEmail.toConfigured,
      handoffEmailToDomain: handoffEmail.toDomain,
      handoffEmailProviderConfigured: handoffEmail.providerConfigured,
      handoffEmailAntiSpamAvailable: true,
      multiIntentDetectorAvailable: true,
      combinedReplyComposerAvailable: true,
      leadContextMemoryCheckerAvailable: true,
      avoidRepeatedInfoRequestAvailable: true,
      priceScopeFirstRuleAvailable: true,
      portfolioInstagramRoutingAvailable: true,
      instagramUrlConfigured,
      portfolioHumanFollowUpTaskAvailable: false,
      replyCoachAvailable: true,
      replyDecisionEngineAvailable: true,
      replyQualityGateAvailable: true,
      validTextNeverEmptyReplyGuard: true,
      noSilenceFallbackAvailable: true,
      safetyRewriteInsteadOfSilence: true,
      repetitionRewriteInsteadOfSilence: true,
      answerActualQuestionFirstRule: true,
      blackBoxReplyRecorderAvailable: true,
      humanTakeoverLockPlanned: true,
      softDeleteAvailable: true,
      restoreAvailable: true,
      bossOnlyHardDeleteAvailable: true,
      deleteAuditAvailable: true,
      humanTakeoverAvailable: true,
      botPauseResumeAvailable: true,
      leadScoringAvailable: true,
      conversationSummaryAvailable: true,
      missionQueueAvailable: true,
      followUpReminderAvailable: true,
      staffRolesAvailable: true,
      settingsPageAvailable: true,
      goldCommandCentreUiAvailable: true,
      inAppQaCentreAvailable: true,
      salesLearningFoundationAvailable: true,
      weeklyBossReportDraftAvailable: true,
      quotationReadinessAvailable: true,
      questionBankAvailable: true,
      questionBankCategories: questionBank.categories,
      questionBankExamples: questionBank.exampleQuestions,
      fallbackBrainAvailable: true,
      safetyValidatorAvailable: true,
      repetitionCheckerAvailable: true,
      hasSupabaseUrl: envPresent("NEXT_PUBLIC_SUPABASE_URL"),
      hasSupabaseAnonKey: Boolean(getSupabasePublicKey()),
      hasServiceRoleKey: hasSupabaseAdminEnv(),
      liveInboundEnabled: envFlag("WHATSAPP_LIVE_INBOUND_ENABLED"),
      testAutoReplyEnabled: envFlag("WHATSAPP_TEST_AUTO_REPLY_ENABLED"),
      publicAutoReplyEnabled: envFlag("WHATSAPP_PUBLIC_AUTO_REPLY_ENABLED"),
      testMode: envFlag("WHATSAPP_TEST_MODE", true),
      hasWhatsappVerifyToken: envPresent("WHATSAPP_VERIFY_TOKEN"),
      hasWhatsappAppSecret: webhookSignatureEnforced,
      hasWhatsappPhoneNumberId: envPresent("WHATSAPP_PHONE_NUMBER_ID"),
      hasWhatsappAccessToken: envPresent("WHATSAPP_ACCESS_TOKEN"),
      hasWhatsappBusinessNumber: envPresent("WHATSAPP_BUSINESS_NUMBER"),
      openaiWhatsappReplyEnabled: openAiWhatsApp.enabled,
      hasOpenaiApiKey: openAiWhatsApp.keyConfigured,
      whatsappReplyBrainDebug: openAiWhatsApp.debug,
      calendarBookingEnabled: calendar.bookingEnabled,
      calendarBossApprovalRequired: calendar.bossApprovalRequired,
      calendarAutoBookingEnabled: calendar.autoBookingEnabled,
      googleCalendarConnected: calendar.googleCalendarConnected,
      hasGoogleCalendarId: calendar.calendarIdConfigured,
      hasCalendarTimezone: calendar.hasCalendarTimezone
    });
  } catch {
    return NextResponse.json({
      ok: true,
      version: "v11_1_3_outbound_hotfix",
      salesBrainVersion: "v10.2.1",
      securityVersion: "v10.2.2",
      uiVersion: "v11.1.3",
      underlyingSalesComposerVersion: "v9_clean_core",
      runtime: "vercel",
      webhookSignatureVerificationAvailable: true,
      webhookSignatureEnforced: false,
      crossInstanceConversationLeaseAvailable: false,
      atomicReplyReservationAvailable: false,
      finalPreSendContextRefreshAvailable: false,
      newerInboundStaleReplySuppressionAvailable: false,
      inboundBurstSettleAvailable: false,
      historicalDuplicateDisplayCollapseAvailable: false,
      legacyIntentClassificationLabelsAvailable: false,
      leadFactsInboundEvidenceOnly: false,
      databaseConnected: false,
      migration027Ready: false,
      migration028Ready: false,
      migration031Ready: false,
      intakeProfileSchemaReady: false,
      inboundFailureRecoveryAvailable: false,
      schemaCompatibilityRetryAvailable: true,
      productionSchemaDeploymentGateAvailable: true,
      bossOnlyFailureRecoveryWorkspaceAvailable: true,
      noSendFailureRecoveryAvailable: true,
      authenticatedQaReleaseGateAvailable: true,
      trustedWebhookLeadControlReadAvailable: true,
      unexpectedNoSendTelemetryAvailable: true,
      outboundTerminalProofRequired: true,
      whatsappRecoveryProofSchemaReady: false,
      unresolvedPreservedInboundCount: 0,
      recoveredInboundLast24hCount: 0,
      lastPreservedInboundFailureAt: null,
      lastPreservedInboundRecoveryAt: null,
      freshV1112RealInboundProofObserved: false,
      freshV1112RealInboundProofAt: null,
      freshV1113RealInboundProofObserved: false,
      freshV1113RealInboundProofAt: null,
      freshV1113RealOutboundProofObserved: false,
      freshV1113RealOutboundProofAt: null,
      whatsappProductionSafetyReady: false,
      whatsappProductionSafetyReason: "health_check_failed",
      intentGateAvailable: false,
      leadEligibilityGateAvailable: false,
      nonSalesRoutingAvailable: false,
      oneTimeVendorAcknowledgementAvailable: false,
      latestUnansweredQuestionAvailable: false,
      semanticDuplicateGuardAvailable: false,
      semanticDuplicateThreshold: 0.85,
      semanticDuplicateReplyWindow: 5,
      humanTakeoverFinalGuardAvailable: false,
      nonSalesSalesSurfaceExclusionAvailable: false,
      rawInboundBeforeIntentClassificationAvailable: false,
      intentGateAuditAvailable: false,
      manualIntentOverrideAvailable: false,
      classifierFailureSafeSuppressionAvailable: false,
      deterministicIntentBudgetMs: 100,
      intentContextMessageLimit: 10,
      v9ProductionRouteEnabled: false,
      legacyReplyLogicQuarantined: false,
      singleReplyCoreOnly: false,
      manualWhatsappOutboundReplyAvailable: false,
      inboxLatestActivityFirstAvailable: true,
      inboxQuickSpamRemovalAvailable: true,
      inboxQuickSpamRemovalRecoverable: true,
      inboxStickyComposerAvailable: true,
      inboxDetailsDrawerAvailable: true,
      inboxBulkSpamRemovalAvailable: true,
      inboxMobileQueueChatFlowAvailable: true,
      inboxTabletFullWidthAvailable: true,
      commandCentreUnifiedVisualSystemAvailable: true,
      commandCentreCompactResponsiveShellAvailable: true,
      commandCentreMobileIconNavigationAvailable: true,
      commandCentreRouteLoadingErrorStatesAvailable: true,
      commandCentreReducedMotionAvailable: true,
      inboxKeyboardShortcutsAvailable: true,
      inboxRememberedFilterAvailable: true,
      inboxAccessibleDetailsFocusTrapAvailable: true,
      commandCentreGlobalCommandPaletteAvailable: true,
      operatorPriorityCockpitAvailable: true,
      operatorContextActionPaletteAvailable: true,
      operatorConversationBriefAvailable: true,
      operatorResponseTargetMinutes: 60,
      operatorSavedInboxViewsAvailable: true,
      operatorSpamUndoAvailable: true,
      operatorQueueSyncHealthAvailable: true,
      operatorInboxInitialBundleBudgetKb: 140,
      commandCentreSkipNavigationAvailable: true,
      commandCentreSemanticHeadingHierarchyAvailable: true,
      commandCoreDeferredMapBundleAvailable: true,
      commandCoreInitialBundleBudgetKb: 120,
      commandCentreCrossRouteAccessibilityGateAvailable: true,
      commandCentreUnauthenticatedAccessibilityAvailable: true,
      duplicatePrioritySignalsSuppressedAvailable: true,
      collectionQueueOverflowContainedAvailable: true,
      bossDailyBriefAvailable: false,
      bossOpsNavigationGroupsAvailable: false,
      riskBadgesAvailable: false,
      bossReviewGateAvailable: false,
      quoteSentBossApprovalGateAvailable: false,
      doNotStartGateAvailable: false,
      collectionQueueAvailable: false,
      jbcDefaultPaymentScheduleAvailable: false,
      limmCustomMilestoneScheduleAvailable: false,
      singaporeTimezoneDateSafetyAvailable: false,
      pwaManifestAvailable: false,
      pwaServiceWorkerAvailable: false,
      pwaStandaloneDisplayAvailable: false,
      mobileBottomNavigationAvailable: false,
      cameraPhotoUploadSupportAvailable: false,
      leadConversationTimelineAvailable: false,
      manualTakeoverOnReplyAvailable: false,
      whatsappManualTestSendAvailable: false,
      replaySafeManualReplyPostRedirect: false,
      durableCorrectionMemoryAvailable: false,
      frustrationHandoffLockAvailable: false,
      hypotheticalContextSwitchGuardAvailable: false,
      antiRepeatGuardAvailable: false,
      singleReplyPlannerEnforced: false,
      goldenReplayPackAvailable: false,
      goldenReplayPackCount: 0,
      replayRunnerAvailable: false,
      replayVariationGeneratorAvailable: false,
      memoryBasedReplayAvailable: false,
      publicAutoReplyRecommended: false,
      legacyReplyTemplatesRemovedFromLivePath: false,
      replySourceTraceAvailable: false,
      legacyTemplateBlockedInFinalReplies: false,
      priceReplyUsesV72PlannerOnly: false,
      priceReplyNoScopeAskForSeriousAa: false,
      contextAwareNextUsefulItemAvailable: false,
      priceReplyUsesKnownContext: false,
      priceReplyNoBroadScopeAskForSeriousLandedAa: false,
      priceReplyDoesNotAskReceivedFiles: false,
      portfolioReplyUsesFileContext: false,
      priceReplyUsesKnownProjectContext: false,
      greetingKnownContextNatural: false,
      clientNameRuleAvailable: false,
      reviewReadyStopAskingRefinementAvailable: false,
      receivedFilesNotAskedAgain: false,
      seriousLandedAaNoBroadScopeAsk: false,
      playbookV5SingleReplyPlannerAvailable: false,
      salesMomentClassifierAvailable: false,
      clientPatienceDetectorAvailable: false,
      leadSeriousnessScorerAvailable: false,
      nextBestMoveSelectorAvailable: false,
      humanFeelJudgeAvailable: false,
      stopAskingRuleAvailable: false,
      seriousLandedAaRuleAvailable: false,
      questionBudgetByClientStateAvailable: false,
      directQuestionFirstEnforced: false,
      fileConfidenceStatusAvailable: false,
      clientFacingPlaceholderSuppressionAvailable: false,
      mergedLeadContextContractAvailable: false,
      clientFacingKnownSummaryBuilderAvailable: false,
      fileStatusQuestionIntentAvailable: false,
      floorplanStatusReplyAvailable: false,
      knownContextPersistenceAcrossReplies: false,
      shortPingUsesKnownContextAvailable: false,
      internalPlaceholderNeverClientFacing: false,
      worldClassSalesConversationBrainAvailable: false,
      memoryFirstReplyComposerAvailable: false,
      knownInfoAcknowledgementBeforeQuestions: false,
      shortPingSmartReplyAvailable: false,
      confusionPingSmartReplyAvailable: false,
      alreadyToldYouRecoveryAvailable: false,
      budgetStatementNotPriceQuestionAvailable: false,
      contextAwareMissingInfoQuestionsAvailable: false,
      maxThreeQuestionsDefaultAvailable: false,
      genericFallbackReducedAvailable: false,
      conversationReplayTestAvailable: false,
      intakeKnownInfoAcknowledgementAvailable: false,
      budgetStatementClassificationAvailable: false,
      budgetExpectationNotPriceQuestionAvailable: false,
      intakeMissingInfoDeduplicationAvailable: false,
      addressExtractionAvailable: false,
      timelineExtractionAvailable: false,
      landedAaExtractionAvailable: false,
      finalSafetyFalsePositiveFixAvailable: false,
      safeFallbackFinalValidationAllowed: false,
      ultraSafeFallbackRewriteAvailable: false,
      finalValidationReasonLoggingAvailable: false,
      clientFileStorageAvailable: false,
      supabaseClientFilesBucketConfigured: false,
      leadFilesTableAvailable: false,
      whatsappMediaStorageAvailable: false,
      whatsappImageStorageAvailable: false,
      whatsappDocumentStorageAvailable: false,
      inboxMediaAttachmentVisibilityAvailable: false,
      privateInboxAttachmentRedirectAvailable: false,
      whatsappMediaFetchRetryAvailable: false,
      whatsappMediaManualRecoveryAvailable: false,
      whatsappAttachmentRealtimeRefreshAvailable: false,
      clientUploadLinkAvailable: false,
      secureUploadTokenAvailable: false,
      leadDetailFilePanelAvailable: false,
      clientFilesPageRealDataAvailable: false,
      signedFileUrlAvailable: false,
      fileCategoryDetectionAvailable: false,
      fileStatusTrackingAvailable: false,
      fileReviewWorkflowAvailable: false,
      fileVoidInsteadOfDeleteAvailable: false,
      fileUploadAuditAvailable: false,
      meetingReadinessFileConnectionAvailable: false,
      quotationReadinessFileConnectionAvailable: false,
      strategicCommandCoreAvailable: false,
      commandCoreBetaRouteAvailable: false,
      frostpunkInspiredLayoutAvailable: false,
      commandCoreFinalTouchupAvailable: false,
      commandCoreResourceBarContrastFixed: false,
      commandCoreOperatingPictureCompressed: false,
      commandCoreMapHeroPreserved: false,
      commandCoreBottomPanelsAligned: false,
      commandCoreMapFirstLayoutAvailable: false,
      commandCoreMapFullWidthHeroAvailable: false,
      commandCoreMapSameSizeAsDashboardAvailable: false,
      commandCoreResourceBarReadable: false,
      commandCorePaleResourceCardsRemoved: false,
      commandCoreSidePanelsNoLongerSqueezeMap: false,
      commandCoreWideMapLayoutAvailable: false,
      commandCoreMapDominantLayoutAvailable: false,
      commandCoreMapUsesFullPanelWidth: false,
      topResourceBarAvailable: false,
      marcusDecisionsPanelAvailable: false,
      rightInspectorPanelAvailable: false,
      bottomTimelineStripAvailable: false,
      commandCoreUsesRealDataOnly: false,
      currentDashboardPreserved: false,
      ui100CommandCentrePolishAvailable: false,
      dashboardBossActionClarityAvailable: false,
      marcusToday100PolishAvailable: false,
      leadCards100PolishAvailable: false,
      sidebar100PolishAvailable: false,
      followUpQueueUiPreserved: false,
      leadDetail100PolishAvailable: false,
      emptyStates100PolishAvailable: false,
      mobileUiPolishAvailable: false,
      interactionFeedbackPolishAvailable: false,
      performanceSafeUiPolishAvailable: false,
      officialSingaporeMapPreserved: false,
      mapDefaultZoomStartsAt100: false,
      mapSmoothZoomControlsAvailable: false,
      mapResetClearsPanSelectionTooltip: false,
      mapWheelZoomAvailable: false,
      mapWheelPreventsPageScroll: false,
      mapWheelListenerPassiveFalse: false,
      mapDefaultFitImproved: false,
      mapHorizontalSpaceOptimized: false,
      mapResetClearsSelection: false,
      mapFilterEmptyStatePolished: false,
      mapTopLeftCopyDeduped: false,
      mapHelperTextMovedToBottom: false,
      mapNoStackedStatusLabels: false,
      mapInspectorPanelAvailable: false,
      mapHqMarkerScalePolished: false,
      mapResetButtonFixed: false,
      mapResetRestoresDefaultFit: false,
      mapZoomControlsReliable: false,
      mapZoomBoundsAvailable: false,
      mapZoomPercentAccurate: false,
      mapPanDragAvailable: false,
      mapResetClearsPanAndSelection: false,
      mapAreaClickSummaryAvailable: false,
      mapPinClickSummaryAvailable: false,
      mapHqTooltipAvailable: false,
      mapAreaCountBubblesAvailable: false,
      mapFiltersAffectPinsAvailable: false,
      officialMapGeometryPreserved: false,
      officialSingaporePlanningAreaMapAvailable: false,
      mapFitToBoundsAvailable: false,
      mapCroppingFixed: false,
      areaLabelsBoundedToPolygons: false,
      hqMarkerCentralSingaporeAvailable: false,
      fakeSentosaRemoved: false,
      realSingaporeGeojsonMapAvailable: false,
      realMapGeometryAssetAvailable: false,
      manualBlobMapRemoved: false,
      hqMarkerPostal228397Available: false,
      googleMapsEnabled: false,
      realSingaporeOutlineAvailable: false,
      hqMarkerCentralSingaporeCalibrated: false,
      sentosaScaledShapeRefined: false,
      mapAreaLabelsAvailable: false,
      largeMapHelperBoxRemoved: false,
      smartLeadIntakeAvailable: false,
      meetingPrepBrainAvailable: false,
      lifestyleIntakeAvailable: false,
      householdOccupantsIntakeAvailable: false,
      helperPetsIntakeAvailable: false,
      safetyAccessibilityIntakeAvailable: false,
      budgetExpectationCaptureAvailable: false,
      timelineKeyMoveInCaptureAvailable: false,
      intakeChecklistAvailable: false,
      missingInfoDetectorAvailable: false,
      intakeQuestionLimitAvailable: false,
      maxFiveQuestionsRuleAvailable: false,
      noOverlyTechnicalFirstContactQuestions: false,
      intakeQuestionLimitMin: 0,
      intakeQuestionLimitMax: 0,
      lifestyleOccupantsPetsSafetyAvailable: false,
      budgetExpectationCollectionNoPriceReply: false,
      timelineKeyMoveInCollectionAvailable: false,
      meetingReadinessScoreAvailable: false,
      proposalReadinessScoreAvailable: false,
      leadIntakeProfileStorageAvailable: false,
      leadIntakeAuditTraceAvailable: false,
      accurateSingaporeSvgMapAvailable: false,
      singaporeMainlandSvgAvailable: false,
      sentosaOnlyIslandAvailable: false,
      singaporeMapWideLayoutAvailable: false,
      singaporeMapZoomableAvailable: false,
      singaporeMapPanAvailable: false,
      singaporeMapResetZoomAvailable: false,
      singaporeMapHqMarkerAvailable: false,
      singaporeMapHqPostalCode: "228397",
      singaporeMapSentosaOnlyAvailable: false,
      goldAmberColourSeparationFixed: false,
      accurateSingaporeMapAvailable: false,
      mapNoBlockingOverlayAvailable: false,
      mapBaseAlwaysVisible: false,
      subtleEmptyStateHelperAvailable: false,
      singaporeTacticalMapUiAvailable: false,
      singaporeSilhouetteMapAvailable: false,
      mapEmptyStatePolished: false,
      mapLegendIntegrated: false,
      mapAreaSummaryPanelAvailable: false,
      singaporeMissionMapAvailable: false,
      hybridAreaHeatmapAvailable: false,
      clickableMapPinsAvailable: false,
      mapAreaSummaryAvailable: false,
      mapFiltersAvailable: false,
      privacySafeMapDisplayAvailable: false,
      locationConfidenceAvailable: false,
      localSingaporeLocationParserAvailable: false,
      externalGeocodingEnabled: false,
      mapHidesTestDataByDefault: false,
      salesCollectionMapLayerAvailable: false,
      salesPipelineAvailable: false,
      manualQuotationTrackingAvailable: false,
      monthlySalesTargetsAvailable: false,
      monthlyCollectionTargetsAvailable: false,
      potentialQuotedConfirmedValuesAvailable: false,
      wonLostTrackingAvailable: false,
      leadToProjectConversionAvailable: false,
      paymentCollectionTrackerAvailable: false,
      outstandingReceivablesAvailable: false,
      overdueReceivablesAvailable: false,
      quotationPaymentFollowUpRemindersAvailable: false,
      bossMonthlyReportAvailable: false,
      gstCalculationsEnabled: false,
      taxInvoiceWordingEnabled: false,
      moneyChangeAuditAvailable: false,
      paymentVoidAvailable: false,
      scrollableSidebarAvailable: false,
      usefulMissionRadarAvailable: false,
      radarPriorityLegendAvailable: false,
      radarActionButtonAvailable: false,
      dashboardCompressionAvailable: false,
      zeroStatePolishAvailable: false,
      missionControlUiRefinementAvailable: false,
      marcusTodayHeroPanelAvailable: false,
      leadHeatMeterAvailable: false,
      stickyTopCommandBarAvailable: false,
      compactSystemCoreAvailable: false,
      commandTimelineAvailable: false,
      emptyStatesPolished: false,
      microInteractionsAvailable: false,
      colourHierarchyRefined: false,
      missionControlUiIntegrated: false,
      julesUiIdeasAppliedByCodex: false,
      cockpitGlassmorphismThemeAvailable: false,
      radarGridBackgroundAvailable: false,
      mainActionQueueAvailable: false,
      clientFilesComingSoonOnly: false,
      mockClientFilesRemoved: false,
      fullPhoneNumbersShownInProtectedApp: false,
      v615FollowupPerformancePreserved: false,
      v615TestCleanupPreserved: false,
      followUpQueuePaginationAvailable: false,
      followUpButtonsFixed: false,
      testFollowUpsHiddenByDefault: false,
      liveTestFollowUpCleanupAvailable: false,
      testDataHiddenByDefault: false,
      cleanupDoesNotRunOnPageLoad: false,
      performanceDashboardLimitAvailable: false,
      uiPolishAvailable: false,
      missionControlUxFinalPolishAvailable: false,
      marcusTodayPanelAvailable: false,
      sidebarNavigationGrouped: false,
      topCommandBarAvailable: false,
      focusModeAvailable: false,
      cleanLeadCardsAvailable: false,
      emptyStatesAvailable: false,
      colourHierarchyAvailable: false,
      dashboardDebugClutterRemoved: false,
      clientFilesHiddenUntilRealStorage: false,
      clientFilesMockDataRemoved: false,
      nonGstModeAvailable: true,
      gstRegistered: false,
      missionControlUiAvailable: false,
      futuristicCockpitThemeAvailable: false,
      dashboardDeclutterAvailable: false,
      mainDashboardSystemClutterHidden: false,
      leadDisplayNameCleanerAvailable: false,
      liveTestLeadCleanupAvailable: false,
      inAppCleanupDryRunAvailable: false,
      hardDeleteNoTypingRequired: false,
      hideTestLeadsFromDashboardAvailable: false,
      priceGuideAutomationEnabled: false,
      priceGuideOnHold: true,
      specificWorksBrainAvailable: false,
      antiGenericReplyGateAvailable: false,
      inAppLiveCleanupAvailable: false,
      showHideTestLeadsFilterAvailable: false,
      generatedLeadDisplayCleanupAvailable: false,
      marcusFioCleanupProtectionAvailable: false,
      fionCleanupProtectionAvailable: false,
      premiumGoldCommandCentreThemeAvailable: false,
      largerReadableFontsAvailable: false,
      testLeadCleanupAvailable: false,
      testLeadCleanupDryRunAvailable: false,
      testLeadCleanupSoftDeleteDefault: true,
      humanLikeSalesBrainAvailable: false,
      contextTruthGateAvailable: false,
      singaporeRenovationMeaningBrainAvailable: false,
      naturalReplyComposerAvailable: false,
      safetyGovernorAvailable: false,
      replyQualityJudgeAvailable: false,
      overClaimPreventionAvailable: false,
      localRenovationShortformSupportAvailable: false,
      v6DeepQaAvailable: false,
      v6DeepQaCaseCount: 0,
      v6UltimateDeepQaAvailable: false,
      v6UltimateDeepQaCaseCount: 0,
      optionalAiSalesBrainAvailable: true,
      optionalAiSalesBrainEnabled: false,
      aiDraftReplyEnabled: false,
      aiJsonSchemaValidationAvailable: false,
      deepWhatsappAgentQaAvailable: false,
      webhookPayloadSimulatorAvailable: false,
      mediaContextDetectionAvailable: false,
      floorPlanImageContextAvailable: false,
      avoidAskingForReceivedMediaAvailable: false,
      voiceMessageFallbackAvailable: false,
      voiceTranscriptionEnabled: false,
      singlishIntentSupportAvailable: false,
      singlishRepliesInEnglish: false,
      humanEscalationIntentAvailable: false,
      emailHandoffAvailable: true,
      handoffEmailConfigured: false,
      handoffEmailToConfigured: true,
      handoffEmailToDomain: "gmail.com",
      handoffEmailProviderConfigured: false,
      handoffEmailAntiSpamAvailable: false,
      multiIntentDetectorAvailable: false,
      combinedReplyComposerAvailable: false,
      leadContextMemoryCheckerAvailable: false,
      avoidRepeatedInfoRequestAvailable: false,
      priceScopeFirstRuleAvailable: false,
      portfolioInstagramRoutingAvailable: false,
      instagramUrlConfigured: false,
      portfolioHumanFollowUpTaskAvailable: false,
      replyCoachAvailable: false,
      replyDecisionEngineAvailable: false,
      replyQualityGateAvailable: false,
      validTextNeverEmptyReplyGuard: false,
      noSilenceFallbackAvailable: false,
      safetyRewriteInsteadOfSilence: false,
      repetitionRewriteInsteadOfSilence: false,
      answerActualQuestionFirstRule: false,
      blackBoxReplyRecorderAvailable: false,
      humanTakeoverLockPlanned: true,
      softDeleteAvailable: false,
      restoreAvailable: false,
      bossOnlyHardDeleteAvailable: false,
      deleteAuditAvailable: false,
      humanTakeoverAvailable: false,
      botPauseResumeAvailable: false,
      leadScoringAvailable: false,
      conversationSummaryAvailable: false,
      missionQueueAvailable: false,
      followUpReminderAvailable: false,
      staffRolesAvailable: false,
      settingsPageAvailable: false,
      goldCommandCentreUiAvailable: false,
      inAppQaCentreAvailable: false,
      salesLearningFoundationAvailable: false,
      weeklyBossReportDraftAvailable: false,
      quotationReadinessAvailable: false,
      questionBankAvailable: false,
      questionBankCategories: 0,
      questionBankExamples: 0,
      fallbackBrainAvailable: false,
      safetyValidatorAvailable: false,
      repetitionCheckerAvailable: false,
      hasSupabaseUrl: false,
      hasSupabaseAnonKey: false,
      hasServiceRoleKey: false,
      liveInboundEnabled: false,
      testAutoReplyEnabled: false,
      publicAutoReplyEnabled: false,
      testMode: false,
      hasWhatsappVerifyToken: false,
      hasWhatsappAppSecret: false,
      hasWhatsappPhoneNumberId: false,
      hasWhatsappAccessToken: false,
      hasWhatsappBusinessNumber: false,
      openaiWhatsappReplyEnabled: false,
      hasOpenaiApiKey: false,
      whatsappReplyBrainDebug: false,
      calendarBookingEnabled: false,
      calendarBossApprovalRequired: true,
      calendarAutoBookingEnabled: false,
      googleCalendarConnected: false,
      hasGoogleCalendarId: false,
      hasCalendarTimezone: true
    });
  }
}
