import { NextResponse } from "next/server";
import { getCalendarRuntime } from "@/lib/calendar-config";
import { getHandoffEmailRuntime } from "@/lib/handoff-email";
import { getOpenAiWhatsAppReplyRuntime } from "@/lib/openai-whatsapp-config";
import { getOptionalAiSalesBrainRuntime } from "@/lib/whatsapp-v6/sales-brain";
import { getLimmInstagramUrl } from "@/lib/whatsapp-lead-context";
import { questionBankStats } from "@/lib/whatsapp-question-bank";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

function envPresent(name: string) {
  return Boolean(process.env[name]);
}

function envFlag(name: string, fallback = false) {
  const value = process.env[name];
  if (value === undefined || value === "") return fallback;
  return value.toLowerCase() === "true";
}

export async function GET() {
  try {
    const openAiWhatsApp = getOpenAiWhatsAppReplyRuntime();
    const optionalAiSalesBrain = getOptionalAiSalesBrainRuntime();
    const calendar = getCalendarRuntime();
    const handoffEmail = getHandoffEmailRuntime();
    const questionBank = questionBankStats();
    const instagramUrlConfigured = Boolean(getLimmInstagramUrl());
    return NextResponse.json({
      ok: true,
      version: "v6_ultimate_sales_command_centre",
      salesBrainVersion: "v6.ultimate",
      runtime: "vercel",
      humanLikeSalesBrainAvailable: true,
      contextTruthGateAvailable: true,
      singaporeRenovationMeaningBrainAvailable: true,
      naturalReplyComposerAvailable: true,
      safetyGovernorAvailable: true,
      replyQualityJudgeAvailable: true,
      overClaimPreventionAvailable: true,
      localRenovationShortformSupportAvailable: true,
      v6DeepQaAvailable: true,
      v6DeepQaCaseCount: 156,
      v6UltimateDeepQaAvailable: true,
      v6UltimateDeepQaCaseCount: 224,
      optionalAiSalesBrainAvailable: optionalAiSalesBrain.available,
      optionalAiSalesBrainEnabled: optionalAiSalesBrain.enabled,
      aiDraftReplyEnabled: optionalAiSalesBrain.draftReplyEnabled,
      aiJsonSchemaValidationAvailable: optionalAiSalesBrain.jsonSchemaValidationAvailable,
      deepWhatsappAgentQaAvailable: true,
      webhookPayloadSimulatorAvailable: true,
      mediaContextDetectionAvailable: true,
      floorPlanImageContextAvailable: true,
      avoidAskingForReceivedMediaAvailable: true,
      voiceMessageFallbackAvailable: true,
      voiceTranscriptionEnabled: false,
      singlishIntentSupportAvailable: true,
      singlishRepliesInEnglish: true,
      humanEscalationIntentAvailable: true,
      emailHandoffAvailable: handoffEmail.available,
      handoffEmailConfigured: handoffEmail.configured,
      handoffEmailToConfigured: handoffEmail.toConfigured,
      handoffEmailToDomain: handoffEmail.toDomain,
      handoffEmailProviderConfigured: handoffEmail.providerConfigured,
      handoffEmailAntiSpamAvailable: true,
      multiIntentDetectorAvailable: true,
      combinedReplyComposerAvailable: true,
      leadContextMemoryCheckerAvailable: true,
      avoidRepeatedInfoRequestAvailable: true,
      priceScopeFirstRuleAvailable: true,
      portfolioInstagramRoutingAvailable: true,
      instagramUrlConfigured,
      portfolioHumanFollowUpTaskAvailable: false,
      replyCoachAvailable: true,
      replyDecisionEngineAvailable: true,
      replyQualityGateAvailable: true,
      validTextNeverEmptyReplyGuard: true,
      noSilenceFallbackAvailable: true,
      safetyRewriteInsteadOfSilence: true,
      repetitionRewriteInsteadOfSilence: true,
      answerActualQuestionFirstRule: true,
      blackBoxReplyRecorderAvailable: true,
      humanTakeoverLockPlanned: true,
      softDeleteAvailable: true,
      restoreAvailable: true,
      bossOnlyHardDeleteAvailable: true,
      deleteAuditAvailable: true,
      humanTakeoverAvailable: true,
      botPauseResumeAvailable: true,
      leadScoringAvailable: true,
      conversationSummaryAvailable: true,
      missionQueueAvailable: true,
      followUpReminderAvailable: true,
      staffRolesAvailable: true,
      settingsPageAvailable: true,
      goldCommandCentreUiAvailable: true,
      inAppQaCentreAvailable: true,
      salesLearningFoundationAvailable: true,
      weeklyBossReportDraftAvailable: true,
      quotationReadinessAvailable: true,
      questionBankAvailable: true,
      questionBankCategories: questionBank.categories,
      questionBankExamples: questionBank.exampleQuestions,
      fallbackBrainAvailable: true,
      safetyValidatorAvailable: true,
      repetitionCheckerAvailable: true,
      hasSupabaseUrl: envPresent("NEXT_PUBLIC_SUPABASE_URL"),
      hasSupabaseAnonKey: envPresent("NEXT_PUBLIC_SUPABASE_ANON_KEY"),
      hasServiceRoleKey: envPresent("SUPABASE_SERVICE_ROLE_KEY"),
      liveInboundEnabled: envFlag("WHATSAPP_LIVE_INBOUND_ENABLED"),
      testAutoReplyEnabled: envFlag("WHATSAPP_TEST_AUTO_REPLY_ENABLED"),
      publicAutoReplyEnabled: envFlag("WHATSAPP_PUBLIC_AUTO_REPLY_ENABLED"),
      testMode: envFlag("WHATSAPP_TEST_MODE", true),
      hasWhatsappVerifyToken: envPresent("WHATSAPP_VERIFY_TOKEN"),
      hasWhatsappPhoneNumberId: envPresent("WHATSAPP_PHONE_NUMBER_ID"),
      hasWhatsappAccessToken: envPresent("WHATSAPP_ACCESS_TOKEN"),
      hasWhatsappBusinessNumber: envPresent("WHATSAPP_BUSINESS_NUMBER"),
      openaiWhatsappReplyEnabled: openAiWhatsApp.enabled,
      hasOpenaiApiKey: openAiWhatsApp.keyConfigured,
      whatsappReplyBrainDebug: openAiWhatsApp.debug,
      calendarBookingEnabled: calendar.bookingEnabled,
      calendarBossApprovalRequired: calendar.bossApprovalRequired,
      calendarAutoBookingEnabled: calendar.autoBookingEnabled,
      googleCalendarConnected: calendar.googleCalendarConnected,
      hasGoogleCalendarId: calendar.calendarIdConfigured,
      hasCalendarTimezone: calendar.hasCalendarTimezone
    });
  } catch {
    return NextResponse.json({
      ok: true,
      version: "v6_ultimate_sales_command_centre",
      salesBrainVersion: "v6.ultimate",
      runtime: "vercel",
      humanLikeSalesBrainAvailable: false,
      contextTruthGateAvailable: false,
      singaporeRenovationMeaningBrainAvailable: false,
      naturalReplyComposerAvailable: false,
      safetyGovernorAvailable: false,
      replyQualityJudgeAvailable: false,
      overClaimPreventionAvailable: false,
      localRenovationShortformSupportAvailable: false,
      v6DeepQaAvailable: false,
      v6DeepQaCaseCount: 0,
      v6UltimateDeepQaAvailable: false,
      v6UltimateDeepQaCaseCount: 0,
      optionalAiSalesBrainAvailable: true,
      optionalAiSalesBrainEnabled: false,
      aiDraftReplyEnabled: false,
      aiJsonSchemaValidationAvailable: false,
      deepWhatsappAgentQaAvailable: false,
      webhookPayloadSimulatorAvailable: false,
      mediaContextDetectionAvailable: false,
      floorPlanImageContextAvailable: false,
      avoidAskingForReceivedMediaAvailable: false,
      voiceMessageFallbackAvailable: false,
      voiceTranscriptionEnabled: false,
      singlishIntentSupportAvailable: false,
      singlishRepliesInEnglish: false,
      humanEscalationIntentAvailable: false,
      emailHandoffAvailable: true,
      handoffEmailConfigured: false,
      handoffEmailToConfigured: true,
      handoffEmailToDomain: "gmail.com",
      handoffEmailProviderConfigured: false,
      handoffEmailAntiSpamAvailable: false,
      multiIntentDetectorAvailable: false,
      combinedReplyComposerAvailable: false,
      leadContextMemoryCheckerAvailable: false,
      avoidRepeatedInfoRequestAvailable: false,
      priceScopeFirstRuleAvailable: false,
      portfolioInstagramRoutingAvailable: false,
      instagramUrlConfigured: false,
      portfolioHumanFollowUpTaskAvailable: false,
      replyCoachAvailable: false,
      replyDecisionEngineAvailable: false,
      replyQualityGateAvailable: false,
      validTextNeverEmptyReplyGuard: false,
      noSilenceFallbackAvailable: false,
      safetyRewriteInsteadOfSilence: false,
      repetitionRewriteInsteadOfSilence: false,
      answerActualQuestionFirstRule: false,
      blackBoxReplyRecorderAvailable: false,
      humanTakeoverLockPlanned: true,
      softDeleteAvailable: false,
      restoreAvailable: false,
      bossOnlyHardDeleteAvailable: false,
      deleteAuditAvailable: false,
      humanTakeoverAvailable: false,
      botPauseResumeAvailable: false,
      leadScoringAvailable: false,
      conversationSummaryAvailable: false,
      missionQueueAvailable: false,
      followUpReminderAvailable: false,
      staffRolesAvailable: false,
      settingsPageAvailable: false,
      goldCommandCentreUiAvailable: false,
      inAppQaCentreAvailable: false,
      salesLearningFoundationAvailable: false,
      weeklyBossReportDraftAvailable: false,
      quotationReadinessAvailable: false,
      questionBankAvailable: false,
      questionBankCategories: 0,
      questionBankExamples: 0,
      fallbackBrainAvailable: false,
      safetyValidatorAvailable: false,
      repetitionCheckerAvailable: false,
      hasSupabaseUrl: false,
      hasSupabaseAnonKey: false,
      hasServiceRoleKey: false,
      liveInboundEnabled: false,
      testAutoReplyEnabled: false,
      publicAutoReplyEnabled: false,
      testMode: false,
      hasWhatsappVerifyToken: false,
      hasWhatsappPhoneNumberId: false,
      hasWhatsappAccessToken: false,
      hasWhatsappBusinessNumber: false,
      openaiWhatsappReplyEnabled: false,
      hasOpenaiApiKey: false,
      whatsappReplyBrainDebug: false,
      calendarBookingEnabled: false,
      calendarBossApprovalRequired: true,
      calendarAutoBookingEnabled: false,
      googleCalendarConnected: false,
      hasGoogleCalendarId: false,
      hasCalendarTimezone: true
    });
  }
}
