import { buildQuotationReadiness } from "./quotation-readiness";
import type { ApprovalRequest, AuditLog, FollowUp, Lead, PaymentRecord, ProjectAccount, QuotationPackage } from "./types";

export const mockLeads: Lead[] = [
  {
    id: "lead-001",
    clientName: "Daniel Tan",
    phone: "+65 8123 4567",
    source: "WhatsApp",
    division: "LIMM Works",
    propertyType: "Old inter-terrace",
    serviceType: "Landed A&A",
    scopeSummary: "Wet kitchen extension, bathrooms, roof leak area, rewiring",
    leadScore: 94,
    leadCategory: "Hot",
    status: "Waiting Boss Approval",
    missingInfo: ["floor_plan", "site_photos", "preferred_contact_time"],
    aiRecommendedNextAction: "Ask for floor plan, site photos, and preferred contact time. Boss review required.",
    bossApprovalNeeded: true,
    appointmentSuitable: true,
    appointmentType: "site_discussion",
    appointmentReadiness: 70,
    quotationReadiness: 62,
    lastClientMessage: "Can prepare quotation and arrange site discussion this week?",
    lastReplyAt: null,
    createdAt: "2026-05-28T09:10:00+08:00",
    updatedAt: "2026-05-28T11:18:00+08:00",
    preferredContactTime: "",
    riskFlags: ["landed_a_and_a", "wet_works", "approval_review_needed"],
    salesStage: "Quotation Needed",
    potentialValue: 120000,
    expectedCloseDate: "2026-07-08T18:00:00+08:00",
    salesNextAction: "Boss quote review required before quotation is sent."
  },
  {
    id: "lead-002",
    clientName: "Ms Lim",
    phone: "+65 9000 1122",
    source: "Website",
    division: "LIMM Works",
    propertyType: "Condo",
    serviceType: "Full renovation",
    scopeSummary: "Kitchen, two bathrooms, vinyl, carpentry, lighting",
    leadScore: 76,
    leadCategory: "Warm",
    status: "Ready To Book",
    missingInfo: ["site_photos"],
    aiRecommendedNextAction: "Offer initial project review slot after site photos are received.",
    bossApprovalNeeded: false,
    appointmentSuitable: true,
    appointmentType: "initial_project_review",
    appointmentReadiness: 82,
    quotationReadiness: 50,
    lastClientMessage: "I can speak tomorrow afternoon.",
    lastReplyAt: "2026-05-28T10:15:00+08:00",
    createdAt: "2026-05-28T08:45:00+08:00",
    updatedAt: "2026-05-28T10:15:00+08:00",
    preferredContactTime: "Tomorrow afternoon",
    riskFlags: ["mcst_rules"],
    salesStage: "Site Visit Needed",
    potentialValue: 68000,
    followUpDate: "2026-06-27T16:00:00+08:00",
    salesNextAction: "Confirm site photos and appointment timing."
  },
  {
    id: "lead-003",
    clientName: "Apex Clinic",
    phone: "+65 6777 2323",
    source: "Referral",
    division: "LIMM Works",
    propertyType: "Commercial clinic",
    serviceType: "Commercial renovation",
    scopeSummary: "Treatment rooms, reception, plumbing, electrical, privacy",
    leadScore: 88,
    leadCategory: "Hot",
    status: "Quotation Readiness",
    missingInfo: ["landlord_requirements", "floor_plan"],
    aiRecommendedNextAction: "Prepare boss approval pack and request landlord requirements.",
    bossApprovalNeeded: true,
    appointmentSuitable: true,
    appointmentType: "site_discussion",
    appointmentReadiness: 64,
    quotationReadiness: 58,
    lastClientMessage: "I need boss approval first. Can prepare budget direction?",
    lastReplyAt: null,
    createdAt: "2026-05-28T11:05:00+08:00",
    updatedAt: "2026-05-28T11:24:00+08:00",
    preferredContactTime: "Weekday 3pm",
    riskFlags: ["commercial", "landlord_approval", "privacy_requirements"],
    salesStage: "Quotation Needed",
    potentialValue: 90000,
    salesNextAction: "Collect landlord requirements before boss review."
  },
  {
    id: "lead-004",
    clientName: "Carpentry Enquiry",
    phone: "+65 8555 0101",
    source: "Instagram",
    division: "Carpentry Works",
    propertyType: "Condo",
    serviceType: "Carpentry",
    scopeSummary: "Wardrobe, shoe cabinet, kitchen cabinet adjustment",
    leadScore: 48,
    leadCategory: "Cold",
    status: "Awaiting Client",
    missingInfo: ["measurements", "photos", "material_preference"],
    aiRecommendedNextAction: "Request site photos, rough dimensions, and material direction.",
    bossApprovalNeeded: false,
    appointmentSuitable: false,
    appointmentType: "manager_call",
    appointmentReadiness: 35,
    quotationReadiness: 25,
    lastClientMessage: "How much for wardrobe?",
    lastReplyAt: "2026-05-27T18:20:00+08:00",
    createdAt: "2026-05-27T17:55:00+08:00",
    updatedAt: "2026-05-27T18:20:00+08:00",
    preferredContactTime: "",
    riskFlags: ["price_sensitive"],
    salesStage: "Info Requested",
    potentialValue: 8000,
    followUpDate: "2026-06-26T17:00:00+08:00"
  },
  {
    id: "lead-005",
    clientName: "Demo Works Enquiry",
    phone: "+65 8111 0202",
    source: "Website",
    division: "Demo Works",
    propertyType: "Commercial unit",
    serviceType: "Hacking and disposal",
    scopeSummary: "Hacking-only enquiry for partition removal, site protection, and debris disposal",
    leadScore: 52,
    leadCategory: "Warm",
    status: "Awaiting Client",
    missingInfo: ["site_photos", "property_management_requirements"],
    aiRecommendedNextAction: "Request site photos, affected area details, and management requirements before review.",
    bossApprovalNeeded: false,
    appointmentSuitable: false,
    appointmentType: "manager_call",
    appointmentReadiness: 40,
    quotationReadiness: 30,
    lastClientMessage: "Need hacking and disposal only for a small commercial unit.",
    lastReplyAt: null,
    createdAt: "2026-05-28T12:05:00+08:00",
    updatedAt: "2026-05-28T12:05:00+08:00",
    preferredContactTime: "",
    riskFlags: ["hacking_demo", "site_protection"],
    salesStage: "Qualified",
    potentialValue: 12000
  },
  {
    id: "lead-006",
    clientName: "Serene Ong",
    phone: "+65 9222 7711",
    source: "Referral",
    division: "LIMM Works",
    propertyType: "Condo",
    serviceType: "Full home renovation",
    scopeSummary: "Condo resale renovation with kitchen, bathrooms, flooring, painting, electrical and carpentry",
    leadScore: 82,
    leadCategory: "Hot",
    status: "Quotation Readiness",
    missingInfo: [],
    aiRecommendedNextAction: "Won job. Check deposit and job-start gate before allowing site start.",
    bossApprovalNeeded: false,
    appointmentSuitable: true,
    appointmentType: "site_discussion",
    appointmentReadiness: 92,
    quotationReadiness: 88,
    lastClientMessage: "We accepted the quote. Can your team start next week after condo approval?",
    lastReplyAt: "2026-06-25T15:30:00+08:00",
    createdAt: "2026-06-10T10:05:00+08:00",
    updatedAt: "2026-06-25T15:30:00+08:00",
    preferredContactTime: "Weekday afternoon",
    riskFlags: ["mcst_rules", "tight_timeline"],
    salesStage: "Won",
    quotationStatus: "Accepted",
    quotedAmount: 62000,
    confirmedValue: 62000,
    wonDate: "2026-06-25T15:30:00+08:00",
    projectId: "project-lead-006",
    projectAddress: "Condo project, central Singapore",
    salesNextAction: "Collect deposit and clear start gate before work starts."
  },
  {
    id: "qa-lead-condo",
    clientName: "QA_TEST_LIMM_CONDO",
    phone: "+65 8888 1001",
    source: "QA_E2E_MODE",
    division: "LIMM Works",
    propertyType: "Condo",
    serviceType: "Full renovation",
    scopeSummary: "QA condo renovation with MCST and protection checks.",
    leadScore: 84,
    leadCategory: "Hot",
    status: "Quotation Readiness",
    missingInfo: [],
    aiRecommendedNextAction: "QA only: submit quotation package for boss review.",
    bossApprovalNeeded: true,
    appointmentSuitable: true,
    appointmentType: "site_discussion",
    appointmentReadiness: 90,
    quotationReadiness: 88,
    lastClientMessage: "QA_RUN_ID condo workflow. Please do not contact.",
    lastReplyAt: null,
    createdAt: "2026-06-27T09:00:00+08:00",
    updatedAt: "2026-06-27T09:00:00+08:00",
    preferredContactTime: "QA only",
    riskFlags: ["condo_mcst", "tight_timeline"],
    salesStage: "Quotation Needed",
    potentialValue: 75000,
    salesNextAction: "QA dry-run quotation workflow.",
    isTest: true
  },
  {
    id: "qa-lead-landed-aa",
    clientName: "QA_TEST_LANDED_AA",
    phone: "+65 8888 1004",
    source: "QA_E2E_MODE",
    division: "LIMM Works",
    propertyType: "Landed terrace",
    serviceType: "Landed A&A",
    scopeSummary: "QA landed A&A with structural wall hacking, waterproofing, roof/drainage, and tight timeline.",
    leadScore: 91,
    leadCategory: "Hot",
    status: "Quotation Readiness",
    missingInfo: [],
    aiRecommendedNextAction: "QA only: boss review and site visit first.",
    bossApprovalNeeded: true,
    appointmentSuitable: true,
    appointmentType: "site_discussion",
    appointmentReadiness: 88,
    quotationReadiness: 86,
    lastClientMessage: "QA landed A&A workflow. Please do not contact.",
    lastReplyAt: null,
    createdAt: "2026-06-27T09:07:00+08:00",
    updatedAt: "2026-06-27T09:07:00+08:00",
    preferredContactTime: "QA only",
    riskFlags: ["landed_a_and_a", "structural", "wall_hacking", "waterproofing", "roof_drainage", "tight_timeline", "high_value_job"],
    salesStage: "Quotation Needed",
    potentialValue: 180000,
    salesNextAction: "QA dry-run landed boss review.",
    isTest: true
  },
  {
    id: "qa-lead-condo-mcst",
    clientName: "QA_TEST_CONDO_MCST",
    phone: "+65 8888 1009",
    source: "QA_E2E_MODE",
    division: "LIMM Works",
    propertyType: "Condo",
    serviceType: "Condo renovation",
    scopeSummary: "QA condo renovation specifically for MCST and protection start-gate checks.",
    leadScore: 82,
    leadCategory: "Hot",
    status: "Quotation Readiness",
    missingInfo: [],
    aiRecommendedNextAction: "QA only: accept quote and test MCST/protection blockers.",
    bossApprovalNeeded: true,
    appointmentSuitable: true,
    appointmentType: "site_discussion",
    appointmentReadiness: 88,
    quotationReadiness: 90,
    lastClientMessage: "QA condo MCST workflow. Please do not contact.",
    lastReplyAt: null,
    createdAt: "2026-06-27T09:07:30+08:00",
    updatedAt: "2026-06-27T09:07:30+08:00",
    preferredContactTime: "QA only",
    riskFlags: ["condo_mcst", "site_protection"],
    salesStage: "Quotation Needed",
    potentialValue: 65000,
    salesNextAction: "QA dry-run condo MCST workflow.",
    isTest: true
  },
  {
    id: "qa-lead-jbc-carpentry",
    clientName: "QA_TEST_JBC_CARPENTRY",
    phone: "+65 8888 1005",
    source: "QA_E2E_MODE",
    division: "Carpentry Works",
    propertyType: "Condo",
    serviceType: "Carpentry package",
    scopeSummary: "QA carpentry job for wardrobe, kitchen cabinets, and shoe cabinet.",
    leadScore: 78,
    leadCategory: "Warm",
    status: "Quotation Readiness",
    missingInfo: [],
    aiRecommendedNextAction: "QA only: accept quote and verify 50/40/10 collection schedule.",
    bossApprovalNeeded: true,
    appointmentSuitable: true,
    appointmentType: "site_discussion",
    appointmentReadiness: 84,
    quotationReadiness: 90,
    lastClientMessage: "QA JBC carpentry workflow. Please do not contact.",
    lastReplyAt: null,
    createdAt: "2026-06-27T09:08:00+08:00",
    updatedAt: "2026-06-27T09:08:00+08:00",
    preferredContactTime: "QA only",
    riskFlags: ["price_sensitive", "scope_unclear"],
    salesStage: "Quotation Needed",
    potentialValue: 30000,
    salesNextAction: "QA dry-run carpentry quotation workflow.",
    isTest: true
  },
  {
    id: "qa-lead-revision",
    clientName: "QA_TEST_REVISION_FLOW",
    phone: "+65 8888 1006",
    source: "QA_E2E_MODE",
    division: "LIMM Works",
    propertyType: "HDB",
    serviceType: "Renovation revision",
    scopeSummary: "QA revision workflow with v1 hold and v2 approval.",
    leadScore: 72,
    leadCategory: "Warm",
    status: "Quotation Readiness",
    missingInfo: [],
    aiRecommendedNextAction: "QA only: request revision then approve v2.",
    bossApprovalNeeded: true,
    appointmentSuitable: true,
    appointmentType: "manager_call",
    appointmentReadiness: 80,
    quotationReadiness: 87,
    lastClientMessage: "QA revision workflow. Please do not contact.",
    lastReplyAt: null,
    createdAt: "2026-06-27T09:09:00+08:00",
    updatedAt: "2026-06-27T09:09:00+08:00",
    preferredContactTime: "QA only",
    riskFlags: ["scope_unclear"],
    salesStage: "Quotation Needed",
    potentialValue: 42000,
    salesNextAction: "QA dry-run revision workflow.",
    isTest: true
  },
  {
    id: "qa-lead-rejected",
    clientName: "QA_TEST_CLIENT_REJECTED",
    phone: "+65 8888 1007",
    source: "QA_E2E_MODE",
    division: "LIMM Works",
    propertyType: "Condo",
    serviceType: "Renovation rejected quote",
    scopeSummary: "QA client rejected quotation should not create project or payment schedule.",
    leadScore: 66,
    leadCategory: "Warm",
    status: "Quotation Readiness",
    missingInfo: [],
    aiRecommendedNextAction: "QA only: mark client rejected.",
    bossApprovalNeeded: true,
    appointmentSuitable: true,
    appointmentType: "manager_call",
    appointmentReadiness: 78,
    quotationReadiness: 85,
    lastClientMessage: "QA rejection workflow. Please do not contact.",
    lastReplyAt: null,
    createdAt: "2026-06-27T09:11:00+08:00",
    updatedAt: "2026-06-27T09:11:00+08:00",
    preferredContactTime: "QA only",
    riskFlags: ["price_sensitive"],
    salesStage: "Quotation Needed",
    potentialValue: 28000,
    salesNextAction: "QA dry-run rejected quote workflow.",
    isTest: true
  },
  {
    id: "qa-lead-role",
    clientName: "QA_TEST_ROLE_PERMISSION",
    phone: "+65 8888 1008",
    source: "QA_E2E_MODE",
    division: "LIMM Works",
    propertyType: "HDB",
    serviceType: "Permission test quotation",
    scopeSummary: "QA role permission quote package.",
    leadScore: 70,
    leadCategory: "Warm",
    status: "Quotation Readiness",
    missingInfo: [],
    aiRecommendedNextAction: "QA only: role permission checks.",
    bossApprovalNeeded: true,
    appointmentSuitable: true,
    appointmentType: "manager_call",
    appointmentReadiness: 75,
    quotationReadiness: 86,
    lastClientMessage: "QA role permission workflow. Please do not contact.",
    lastReplyAt: null,
    createdAt: "2026-06-27T09:12:00+08:00",
    updatedAt: "2026-06-27T09:12:00+08:00",
    preferredContactTime: "QA only",
    riskFlags: ["approval_review_needed"],
    salesStage: "Quotation Needed",
    potentialValue: 35000,
    salesNextAction: "QA dry-run role permission workflow.",
    isTest: true
  },
  {
    id: "qa-lead-miamamun",
    clientName: "QA_TEST_miamamun52582",
    phone: "+65 8888 1002",
    source: "v3_live_test",
    division: "LIMM Works",
    propertyType: "HDB",
    serviceType: "Dummy renovation",
    scopeSummary: "Generated test dirty record for data hygiene.",
    leadScore: 5,
    leadCategory: "Low Fit",
    status: "New Enquiry",
    missingInfo: ["qa_marker"],
    aiRecommendedNextAction: "Hide from production dashboards.",
    bossApprovalNeeded: false,
    appointmentReadiness: 0,
    quotationReadiness: 0,
    lastClientMessage: "v3_live_test generated test approval record.",
    lastReplyAt: null,
    createdAt: "2026-06-27T09:05:00+08:00",
    updatedAt: "2026-06-27T09:05:00+08:00",
    preferredContactTime: "",
    riskFlags: ["qa"],
    salesStage: "New Lead",
    isTest: true
  },
  {
    id: "qa-lead-semon",
    clientName: "QA_TEST_semon",
    phone: "+65 8888 1003",
    source: "QA_E2E_MODE",
    division: "LIMM Works",
    propertyType: "Sample",
    serviceType: "Demo approval",
    scopeSummary: "Test approval generated by Playwright dry-run.",
    leadScore: 3,
    leadCategory: "Low Fit",
    status: "Waiting Boss Approval",
    missingInfo: ["sample"],
    aiRecommendedNextAction: "Hide from production dashboards.",
    bossApprovalNeeded: true,
    appointmentReadiness: 0,
    quotationReadiness: 0,
    lastClientMessage: "Test approval QA sample.",
    lastReplyAt: null,
    createdAt: "2026-06-27T09:06:00+08:00",
    updatedAt: "2026-06-27T09:06:00+08:00",
    preferredContactTime: "",
    riskFlags: ["qa"],
    salesStage: "Qualified",
    isTest: true
  }
];

export const mockProjectAccounts: ProjectAccount[] = [
  {
    id: "project-lead-006",
    leadId: "lead-006",
    clientName: "Serene Ong",
    phone: "+65 9222 7711",
    propertyType: "Condo",
    scopeSummary: "Condo resale renovation with kitchen, bathrooms, flooring, painting, electrical and carpentry",
    quotedAmount: 62000,
    confirmedValue: 62000,
    notes: "LIMM Works custom milestones may be changed manually after boss review.",
    status: "Deposit Pending",
    sourceLeadId: "lead-006",
    projectAddress: "Condo project, central Singapore",
    planningRegion: "Central Region",
    planningArea: "To be confirmed",
    locationConfidence: "area",
    locationSource: "manual",
    locationNotes: "Mock Mode operational example.",
    createdAt: "2026-06-25T15:30:00+08:00",
    updatedAt: "2026-06-25T15:30:00+08:00"
  },
  {
    id: "project-qa-demo-serene-unlinked",
    leadId: "missing-qa-demo-serene",
    clientName: "QA_TEST_DEMO_SERENE_ONG",
    phone: "+65 8888 1999",
    propertyType: "Sample",
    scopeSummary: "Generated fake/demo unlinked payment record.",
    quotedAmount: 9999,
    confirmedValue: 9999,
    notes: "QA demo orphan project must be hidden from normal collection queue.",
    status: "Deposit Pending",
    sourceLeadId: "missing-qa-demo-serene",
    projectAddress: "QA demo",
    planningRegion: "QA",
    planningArea: "QA",
    locationConfidence: "unknown",
    locationSource: "manual",
    locationNotes: "QA generated demo.",
    createdAt: "2026-06-27T09:20:00+08:00",
    updatedAt: "2026-06-27T09:20:00+08:00",
    isTest: true
  },
  {
    id: "project-qa-lead-condo-mcst",
    leadId: "qa-lead-condo-mcst",
    clientName: "QA_TEST_CONDO_MCST",
    phone: "+65 8888 1009",
    propertyType: "Condo",
    scopeSummary: "QA condo renovation specifically for MCST and protection start-gate checks.",
    quotedAmount: 65000,
    confirmedValue: 65000,
    notes: "QA accepted condo project for MCST/protection blocker tests.",
    status: "Deposit Pending",
    sourceLeadId: "qa-lead-condo-mcst",
    projectAddress: "QA condo MCST",
    planningRegion: "QA",
    planningArea: "QA",
    locationConfidence: "unknown",
    locationSource: "manual",
    locationNotes: "QA generated project.",
    createdAt: "2026-06-27T09:22:00+08:00",
    updatedAt: "2026-06-27T09:22:00+08:00",
    isTest: true
  }
];

export const mockPaymentRecords: PaymentRecord[] = [
  {
    id: "payment-lead-006-deposit",
    projectId: "project-lead-006",
    leadId: "lead-006",
    paymentType: "deposit",
    amount: 31000,
    dueDate: "2026-06-24T18:00:00+08:00",
    receivedDate: null,
    status: "Deposit Requested",
    notes: "JBC default 50% deposit milestone.",
    createdAt: "2026-06-25T15:35:00+08:00",
    updatedAt: "2026-06-25T15:35:00+08:00"
  },
  {
    id: "payment-lead-006-progress",
    projectId: "project-lead-006",
    leadId: "lead-006",
    paymentType: "progress",
    amount: 24800,
    dueDate: "2026-07-15T18:00:00+08:00",
    receivedDate: null,
    status: "Progress Payment Due",
    notes: "JBC default 40% progress milestone.",
    createdAt: "2026-06-25T15:36:00+08:00",
    updatedAt: "2026-06-25T15:36:00+08:00"
  },
  {
    id: "payment-lead-006-final",
    projectId: "project-lead-006",
    leadId: "lead-006",
    paymentType: "final",
    amount: 6200,
    dueDate: "2026-08-15T18:00:00+08:00",
    receivedDate: null,
    status: "Final Payment Due",
    notes: "JBC default 10% final milestone.",
    createdAt: "2026-06-25T15:37:00+08:00",
    updatedAt: "2026-06-25T15:37:00+08:00"
  },
  {
    id: "payment-qa-demo-serene-unlinked",
    projectId: "project-qa-demo-serene-unlinked",
    leadId: "missing-qa-demo-serene",
    paymentType: "deposit",
    amount: 9999,
    dueDate: "2026-06-20T18:00:00+08:00",
    receivedDate: null,
    status: "Deposit Requested",
    notes: "QA_TEST_DEMO_SERENE_ONG generated fake/demo unlinked payment.",
    createdAt: "2026-06-27T09:21:00+08:00",
    updatedAt: "2026-06-27T09:21:00+08:00",
    isTest: true
  },
  {
    id: "payment-qa-condo-mcst-deposit",
    projectId: "project-qa-lead-condo-mcst",
    leadId: "qa-lead-condo-mcst",
    paymentType: "deposit",
    amount: 32500,
    dueDate: "2026-06-27T18:00:00+08:00",
    receivedDate: null,
    status: "Deposit Requested",
    notes: "QA condo MCST 50% deposit milestone.",
    createdAt: "2026-06-27T09:23:00+08:00",
    updatedAt: "2026-06-27T09:23:00+08:00",
    isTest: true
  }
];

export const quotationPackages: QuotationPackage[] = [
  {
    id: "quote-lead-001-v1",
    leadId: "lead-001",
    clientName: "Daniel Tan",
    quotationNumber: "LIMM-Q-2026-001",
    versionNumber: 1,
    status: "Submitted for Boss Review",
    preparedBy: "QA Sales",
    preparedAt: "2026-06-26T10:00:00+08:00",
    submittedForBossReviewAt: "2026-06-26T11:00:00+08:00",
    bossReviewedAt: null,
    bossReviewedBy: "",
    approvedAt: null,
    rejectedAt: null,
    revisionRequestedAt: null,
    sentAt: null,
    sentBy: "",
    acceptedAt: null,
    rejectedByClientAt: null,
    quotationAmount: 120000,
    internalCostEstimate: 92000,
    marginEstimate: 28000,
    expiryDate: "2026-07-15",
    scopeSummary: "Wet kitchen extension, bathrooms, roof leak area, rewiring",
    bossNotes: "Boss to review landed A&A and wet works risk before manual send.",
    revisionNotes: "",
    clientNotes: "",
    fileId: "mock-quote-file-lead-001-v1",
    storageBucket: "client-files",
    storagePath: "mock/quotations/lead-001/v1.pdf",
    originalFileName: "LIMM-Q-2026-001-v1.pdf",
    mimeType: "application/pdf",
    fileSizeBytes: 240000,
    createdAt: "2026-06-26T10:00:00+08:00",
    updatedAt: "2026-06-26T11:00:00+08:00"
  },
  {
    id: "quote-lead-006-v1",
    leadId: "lead-006",
    clientName: "Serene Ong",
    quotationNumber: "LIMM-Q-2026-006",
    versionNumber: 1,
    status: "Accepted",
    preparedBy: "Marcus Lim",
    preparedAt: "2026-06-20T10:00:00+08:00",
    submittedForBossReviewAt: "2026-06-20T11:00:00+08:00",
    bossReviewedAt: "2026-06-20T12:00:00+08:00",
    bossReviewedBy: "Marcus Lim",
    approvedAt: "2026-06-20T12:00:00+08:00",
    rejectedAt: null,
    revisionRequestedAt: null,
    sentAt: "2026-06-21T09:00:00+08:00",
    sentBy: "Marcus Lim",
    acceptedAt: "2026-06-25T15:30:00+08:00",
    rejectedByClientAt: null,
    quotationAmount: 62000,
    internalCostEstimate: 48000,
    marginEstimate: 14000,
    expiryDate: "2026-07-10",
    scopeSummary: "Condo resale renovation with kitchen, bathrooms, flooring, painting, electrical and carpentry",
    bossNotes: "Accepted mock operational example for start gate and collection testing.",
    revisionNotes: "",
    clientNotes: "Client accepted manually.",
    fileId: "mock-quote-file-lead-006-v1",
    storageBucket: "client-files",
    storagePath: "mock/quotations/lead-006/v1.pdf",
    originalFileName: "LIMM-Q-2026-006-v1.pdf",
    mimeType: "application/pdf",
    fileSizeBytes: 210000,
    createdAt: "2026-06-20T10:00:00+08:00",
    updatedAt: "2026-06-25T15:30:00+08:00"
  },
  {
    id: "quote-qa-condo-v1",
    leadId: "qa-lead-condo",
    clientName: "QA_TEST_LIMM_CONDO",
    quotationNumber: "QA-Q-2026-CONDO",
    versionNumber: 1,
    status: "Draft",
    preparedBy: "QA Sales",
    preparedAt: "2026-06-27T10:00:00+08:00",
    submittedForBossReviewAt: null,
    bossReviewedAt: null,
    bossReviewedBy: "",
    approvedAt: null,
    rejectedAt: null,
    revisionRequestedAt: null,
    sentAt: null,
    sentBy: "",
    acceptedAt: null,
    rejectedByClientAt: null,
    quotationAmount: 75000,
    internalCostEstimate: 0,
    marginEstimate: 0,
    expiryDate: "2026-07-20",
    scopeSummary: "QA condo renovation package for dry-run E2E only.",
    bossNotes: "QA_RUN_ID mock quotation. No external action.",
    revisionNotes: "",
    clientNotes: "",
    fileId: "mock-quote-file-qa-condo-v1",
    storageBucket: "client-files",
    storagePath: "mock/quotations/qa-condo/v1.pdf",
    originalFileName: "QA-Q-2026-CONDO-v1.pdf",
    mimeType: "application/pdf",
    fileSizeBytes: 190000,
    createdAt: "2026-06-27T10:00:00+08:00",
    updatedAt: "2026-06-27T10:00:00+08:00",
    qaRunId: "QA_RUN_LOCAL",
    isTest: true
  },
  {
    id: "quote-qa-role-v1",
    leadId: "qa-lead-role",
    clientName: "QA_TEST_ROLE_PERMISSION",
    quotationNumber: "QA-Q-ROLE-001",
    versionNumber: 1,
    status: "Submitted for Boss Review",
    preparedBy: "QA Sales",
    preparedAt: "2026-06-27T10:10:00+08:00",
    submittedForBossReviewAt: "2026-06-27T10:15:00+08:00",
    bossReviewedAt: null,
    bossReviewedBy: "",
    approvedAt: null,
    rejectedAt: null,
    revisionRequestedAt: null,
    sentAt: null,
    sentBy: "",
    acceptedAt: null,
    rejectedByClientAt: null,
    quotationAmount: 35000,
    internalCostEstimate: 0,
    marginEstimate: 0,
    expiryDate: "2026-07-20",
    scopeSummary: "QA role permission quote package.",
    bossNotes: "QA role permission test. No external action.",
    revisionNotes: "",
    clientNotes: "",
    fileId: "mock-quote-file-qa-role-v1",
    storageBucket: "client-files",
    storagePath: "mock/quotations/qa-role/v1.pdf",
    originalFileName: "QA-Q-ROLE-001-v1.pdf",
    mimeType: "application/pdf",
    fileSizeBytes: 190000,
    createdAt: "2026-06-27T10:10:00+08:00",
    updatedAt: "2026-06-27T10:15:00+08:00",
    qaRunId: "QA_RUN_LOCAL",
    isTest: true
  }
];

export const approvalRequests: ApprovalRequest[] = [
  {
    id: "approval-001",
    leadId: "lead-001",
    title: "Hot landed A&A reply approval",
    approvalType: "client_reply",
    reason: "Landed extension and wet works require boss review before appointment confirmation.",
    aiRecommendation: "Approve a careful reply requesting floor plan, photos, and contact time before quotation.",
    proposedReply:
      "Thanks, this can be prepared for an initial project review. Please send the floor plan, site photos, and your preferred contact time so my manager can review the matter properly before any quotation is shared.",
    riskFlags: ["landed_a_and_a", "wet_works", "approval_review_needed"],
    status: "pending",
    requestedAt: "2026-05-28T11:18:00+08:00",
    decidedAt: null,
    decidedBy: "",
    notes: "",
    createdAt: "2026-05-28T11:18:00+08:00"
  },
  {
    id: "approval-002",
    leadId: "lead-003",
    title: "Commercial clinic boss approval",
    approvalType: "appointment_review",
    reason: "Commercial clinic may involve landlord, privacy, plumbing, and approval requirements.",
    aiRecommendation: "Request floor plan, landlord requirements, and confirm appointment only after boss review.",
    proposedReply:
      "For clinic renovation, we should review the floor plan, landlord requirements, plumbing and electrical scope, and privacy requirements before preparing the next step.",
    riskFlags: ["commercial", "landlord_approval", "privacy_requirements"],
    status: "pending",
    requestedAt: "2026-05-28T11:22:00+08:00",
    decidedAt: null,
    decidedBy: "",
    notes: "",
    createdAt: "2026-05-28T11:22:00+08:00"
  },
  {
    id: "approval-qa-test",
    leadId: "qa-lead-semon",
    title: "QA_TEST_Test_approval",
    approvalType: "generated test approval",
    reason: "v3_live_test generated QA/test approval record.",
    aiRecommendation: "Hide from production dashboards.",
    proposedReply: "Do not send. QA dry-run only.",
    riskFlags: ["qa", "test approval"],
    status: "pending",
    requestedAt: "2026-06-27T09:10:00+08:00",
    decidedAt: null,
    decidedBy: "",
    notes: "QA_RUN_ID generated test approval.",
    createdAt: "2026-06-27T09:10:00+08:00"
  }
];

export const followUps: FollowUp[] = [
  {
    id: "follow-001",
    leadId: "lead-004",
    clientName: "Carpentry Enquiry",
    dueAt: "2026-05-28T17:00:00+08:00",
    followupType: "awaiting_photos",
    templateType: "awaiting_photos",
    status: "Due",
    suggestedMessage: "Just checking if you are able to send the site photos and rough dimensions for review.",
    completedAt: null,
    notes: ""
  },
  {
    id: "follow-002",
    leadId: "lead-002",
    clientName: "Ms Lim",
    dueAt: "2026-05-29T10:00:00+08:00",
    followupType: "appointment_offer",
    templateType: "appointment_offer",
    status: "Scheduled",
    suggestedMessage: "We can arrange an initial project review after the site photos are received.",
    completedAt: null,
    notes: ""
  }
];

export const auditLogs: AuditLog[] = [
  {
    id: "audit-001",
    actor: "Mock AI",
    actorType: "system",
    actorName: "Mock AI",
    action: "decision_created",
    entity: "lead-001",
    entityType: "lead",
    entityId: "lead-001",
    summary: "Boss approval required for landed A&A lead.",
    beforeData: null,
    afterData: { bossApprovalNeeded: true },
    metadata: {},
    createdAt: "2026-05-28T11:18:00+08:00"
  },
  {
    id: "audit-002",
    actor: "System",
    actorType: "system",
    actorName: "System",
    action: "slot_engine_checked",
    entity: "appointment_rules",
    entityType: "appointment_rules",
    entityId: "default",
    summary: "Sunday visibility controlled by appointment settings.",
    beforeData: null,
    afterData: { sundayControlledBySettings: true },
    metadata: {},
    createdAt: "2026-05-28T11:20:00+08:00"
  },
  {
    id: "audit-003",
    actor: "System",
    actorType: "system",
    actorName: "System",
    action: "quotation_readiness_checked",
    entity: "lead-003",
    entityType: "quotation_readiness",
    entityId: "lead-003",
    summary: "No renovation pricing generated.",
    beforeData: null,
    afterData: { noPricingGenerated: true },
    metadata: {},
    createdAt: "2026-05-28T11:24:00+08:00"
  }
];

export const quotationRows = mockLeads.map((lead) => ({
  lead,
  readiness: buildQuotationReadiness(lead)
}));
