import { buildQuotationReadiness } from "./quotation-readiness";
import type { ApprovalRequest, AuditLog, FollowUp, Lead } from "./types";

export const mockLeads: Lead[] = [
  {
    id: "lead-001",
    clientName: "Daniel Tan",
    phone: "+65 8123 4567",
    source: "WhatsApp",
    division: "LIMM Works",
    propertyType: "Old inter-terrace",
    serviceType: "Landed A&A",
    scopeSummary: "Wet kitchen extension, bathrooms, roof leak area, rewiring",
    leadScore: 94,
    leadCategory: "Hot",
    status: "Waiting Boss Approval",
    missingInfo: ["floor_plan", "site_photos", "preferred_contact_time"],
    aiRecommendedNextAction: "Ask for floor plan, site photos, and preferred contact time. Boss review required.",
    bossApprovalNeeded: true,
    appointmentSuitable: true,
    appointmentType: "site_discussion",
    appointmentReadiness: 70,
    quotationReadiness: 62,
    lastClientMessage: "Can prepare quotation and arrange site discussion this week?",
    lastReplyAt: null,
    createdAt: "2026-05-28T09:10:00+08:00",
    updatedAt: "2026-05-28T11:18:00+08:00",
    preferredContactTime: "",
    riskFlags: ["landed_a_and_a", "wet_works", "approval_review_needed"]
  },
  {
    id: "lead-002",
    clientName: "Ms Lim",
    phone: "+65 9000 1122",
    source: "Website",
    division: "LIMM Works",
    propertyType: "Condo",
    serviceType: "Full renovation",
    scopeSummary: "Kitchen, two bathrooms, vinyl, carpentry, lighting",
    leadScore: 76,
    leadCategory: "Warm",
    status: "Ready To Book",
    missingInfo: ["site_photos"],
    aiRecommendedNextAction: "Offer initial project review slot after site photos are received.",
    bossApprovalNeeded: false,
    appointmentSuitable: true,
    appointmentType: "initial_project_review",
    appointmentReadiness: 82,
    quotationReadiness: 50,
    lastClientMessage: "I can speak tomorrow afternoon.",
    lastReplyAt: "2026-05-28T10:15:00+08:00",
    createdAt: "2026-05-28T08:45:00+08:00",
    updatedAt: "2026-05-28T10:15:00+08:00",
    preferredContactTime: "Tomorrow afternoon",
    riskFlags: ["mcst_rules"]
  },
  {
    id: "lead-003",
    clientName: "Apex Clinic",
    phone: "+65 6777 2323",
    source: "Referral",
    division: "LIMM Works",
    propertyType: "Commercial clinic",
    serviceType: "Commercial renovation",
    scopeSummary: "Treatment rooms, reception, plumbing, electrical, privacy",
    leadScore: 88,
    leadCategory: "Hot",
    status: "Quotation Readiness",
    missingInfo: ["landlord_requirements", "floor_plan"],
    aiRecommendedNextAction: "Prepare boss approval pack and request landlord requirements.",
    bossApprovalNeeded: true,
    appointmentSuitable: true,
    appointmentType: "site_discussion",
    appointmentReadiness: 64,
    quotationReadiness: 58,
    lastClientMessage: "I need boss approval first. Can prepare budget direction?",
    lastReplyAt: null,
    createdAt: "2026-05-28T11:05:00+08:00",
    updatedAt: "2026-05-28T11:24:00+08:00",
    preferredContactTime: "Weekday 3pm",
    riskFlags: ["commercial", "landlord_approval", "privacy_requirements"]
  },
  {
    id: "lead-004",
    clientName: "Carpentry Enquiry",
    phone: "+65 8555 0101",
    source: "Instagram",
    division: "Carpentry Works",
    propertyType: "Condo",
    serviceType: "Carpentry",
    scopeSummary: "Wardrobe, shoe cabinet, kitchen cabinet adjustment",
    leadScore: 48,
    leadCategory: "Cold",
    status: "Awaiting Client",
    missingInfo: ["measurements", "photos", "material_preference"],
    aiRecommendedNextAction: "Request site photos, rough dimensions, and material direction.",
    bossApprovalNeeded: false,
    appointmentSuitable: false,
    appointmentType: "manager_call",
    appointmentReadiness: 35,
    quotationReadiness: 25,
    lastClientMessage: "How much for wardrobe?",
    lastReplyAt: "2026-05-27T18:20:00+08:00",
    createdAt: "2026-05-27T17:55:00+08:00",
    updatedAt: "2026-05-27T18:20:00+08:00",
    preferredContactTime: "",
    riskFlags: ["price_sensitive"]
  },
  {
    id: "lead-005",
    clientName: "Demo Works Enquiry",
    phone: "+65 8111 0202",
    source: "Website",
    division: "Demo Works",
    propertyType: "Commercial unit",
    serviceType: "Hacking and disposal",
    scopeSummary: "Hacking-only enquiry for partition removal, site protection, and debris disposal",
    leadScore: 52,
    leadCategory: "Warm",
    status: "Awaiting Client",
    missingInfo: ["site_photos", "property_management_requirements"],
    aiRecommendedNextAction: "Request site photos, affected area details, and management requirements before review.",
    bossApprovalNeeded: false,
    appointmentSuitable: false,
    appointmentType: "manager_call",
    appointmentReadiness: 40,
    quotationReadiness: 30,
    lastClientMessage: "Need hacking and disposal only for a small commercial unit.",
    lastReplyAt: null,
    createdAt: "2026-05-28T12:05:00+08:00",
    updatedAt: "2026-05-28T12:05:00+08:00",
    preferredContactTime: "",
    riskFlags: ["hacking_demo", "site_protection"]
  }
];

export const approvalRequests: ApprovalRequest[] = [
  {
    id: "approval-001",
    leadId: "lead-001",
    title: "Hot landed A&A reply approval",
    approvalType: "client_reply",
    reason: "Landed extension and wet works require boss review before appointment confirmation.",
    aiRecommendation: "Approve a careful reply requesting floor plan, photos, and contact time before quotation.",
    proposedReply:
      "Thanks, this can be prepared for an initial project review. Please send the floor plan, site photos, and your preferred contact time so my manager can review the matter properly before any quotation is shared.",
    riskFlags: ["landed_a_and_a", "wet_works", "approval_review_needed"],
    status: "pending",
    requestedAt: "2026-05-28T11:18:00+08:00",
    decidedAt: null,
    decidedBy: "",
    notes: "",
    createdAt: "2026-05-28T11:18:00+08:00"
  },
  {
    id: "approval-002",
    leadId: "lead-003",
    title: "Commercial clinic boss approval",
    approvalType: "appointment_review",
    reason: "Commercial clinic may involve landlord, privacy, plumbing, and approval requirements.",
    aiRecommendation: "Request floor plan, landlord requirements, and confirm appointment only after boss review.",
    proposedReply:
      "For clinic renovation, we should review the floor plan, landlord requirements, plumbing and electrical scope, and privacy requirements before preparing the next step.",
    riskFlags: ["commercial", "landlord_approval", "privacy_requirements"],
    status: "pending",
    requestedAt: "2026-05-28T11:22:00+08:00",
    decidedAt: null,
    decidedBy: "",
    notes: "",
    createdAt: "2026-05-28T11:22:00+08:00"
  }
];

export const followUps: FollowUp[] = [
  {
    id: "follow-001",
    leadId: "lead-004",
    clientName: "Carpentry Enquiry",
    dueAt: "2026-05-28T17:00:00+08:00",
    followupType: "awaiting_photos",
    templateType: "awaiting_photos",
    status: "Due",
    suggestedMessage: "Just checking if you are able to send the site photos and rough dimensions for review.",
    completedAt: null,
    notes: ""
  },
  {
    id: "follow-002",
    leadId: "lead-002",
    clientName: "Ms Lim",
    dueAt: "2026-05-29T10:00:00+08:00",
    followupType: "appointment_offer",
    templateType: "appointment_offer",
    status: "Scheduled",
    suggestedMessage: "We can arrange an initial project review after the site photos are received.",
    completedAt: null,
    notes: ""
  }
];

export const auditLogs: AuditLog[] = [
  {
    id: "audit-001",
    actor: "Mock AI",
    actorType: "system",
    actorName: "Mock AI",
    action: "decision_created",
    entity: "lead-001",
    entityType: "lead",
    entityId: "lead-001",
    summary: "Boss approval required for landed A&A lead.",
    beforeData: null,
    afterData: { bossApprovalNeeded: true },
    metadata: {},
    createdAt: "2026-05-28T11:18:00+08:00"
  },
  {
    id: "audit-002",
    actor: "System",
    actorType: "system",
    actorName: "System",
    action: "slot_engine_checked",
    entity: "appointment_rules",
    entityType: "appointment_rules",
    entityId: "default",
    summary: "Sunday visibility controlled by appointment settings.",
    beforeData: null,
    afterData: { sundayControlledBySettings: true },
    metadata: {},
    createdAt: "2026-05-28T11:20:00+08:00"
  },
  {
    id: "audit-003",
    actor: "System",
    actorType: "system",
    actorName: "System",
    action: "quotation_readiness_checked",
    entity: "lead-003",
    entityType: "quotation_readiness",
    entityId: "lead-003",
    summary: "No renovation pricing generated.",
    beforeData: null,
    afterData: { noPricingGenerated: true },
    metadata: {},
    createdAt: "2026-05-28T11:24:00+08:00"
  }
];

export const quotationRows = mockLeads.map((lead) => ({
  lead,
  readiness: buildQuotationReadiness(lead)
}));
