import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const data = process.env.DEV_BRAIN_RUN_JSON ? JSON.parse(process.env.DEV_BRAIN_RUN_JSON) : null;

const status = data?.status ?? "UNKNOWN";
const authStatus = data?.authTested ? "Authenticated boss browser/write checks ran." : "Authenticated boss checks are MANUAL REQUIRED until test credentials are set.";
const browserStatus = data?.browserCompleted ? "Playwright browser QA completed." : "Playwright browser QA did not complete.";
const openIssues = data?.bugsRemaining?.length ? data.bugsRemaining : ["None known from the latest Dev Brain run."];
const nextAction = data?.nextCodexTask ?? "v6.5.1 Accurate Singapore Map Refinement is ready for controlled deploy proof after the health endpoint shows v6_5_1_accurate_singapore_map_refinement. Next recommended phase: visually verify the dashboard map uses the improved local Singapore outline, LIMM HQ sits around Orchard/Dhoby Ghaut on the mainland, Sentosa is smaller and island-like, area labels are subtle, zoom controls and legend remain, and no external map/geocoding API appears.";

const report = [
  "# ChatGPT Handoff Report",
  "",
  "## Current Phase",
  "",
  "v6.5.1 Accurate Singapore Map Refinement implemented on top of the v6.5 Smart Lead Intake, v6.4.4 Singapore Mission Map, v6.3 Sales + Collection command centre, and v6 Ultimate live WhatsApp CRM pipeline.",
  "",
  "## Latest Report",
  "",
  data?.browserReport ? "`docs/V6_5_1_ACCURATE_SINGAPORE_MAP_REFINEMENT.md`, `docs/V6_5_SMART_LEAD_INTAKE_MEETING_PREP.md`, `docs/V6_4_4_ACCURATE_SINGAPORE_SVG_MAP_FIX.md`, `docs/V6_4_3_SINGAPORE_MAP_ZOOM_HQ_REDESIGN.md`, `docs/V6_4_2_ACCURATE_SINGAPORE_MAP_NO_OVERLAY.md`, `docs/V6_4_1_SINGAPORE_TACTICAL_MAP_UI_POLISH.md`, `docs/V6_4_SINGAPORE_MISSION_MAP.md`, `docs/V6_3_SALES_COLLECTION_COMMAND_CENTRE.md`, `DEV_BRAIN_QA_REPORT.md`, `reports/V6_1_TEST_LEAD_CLEANUP_REPORT.md`, `reports/V6_ULTIMATE_DEEP_QA_REPORT.md`, `docs/V6_1_UI_POLISH_TEST_CLEANUP.md`, `docs/V6_ULTIMATE_SALES_COMMAND_CENTRE.md`, `docs/V6_ULTIMATE_BLUEPRINT.md`, `reports/V6_HUMAN_LIKE_SALES_BRAIN_DEEP_QA_REPORT.md`, `reports/V5_3_2_DEEP_WHATSAPP_AGENT_QA_REPORT.md`, `V4_10_WHATSAPP_LIVE_PASS_REPORT.md`, and `V4_3_AUTHENTICATED_BOSS_BROWSER_WRITE_QA_REPORT.md`." : "`docs/V6_5_1_ACCURATE_SINGAPORE_MAP_REFINEMENT.md`, `docs/V6_5_SMART_LEAD_INTAKE_MEETING_PREP.md`, `docs/V6_4_4_ACCURATE_SINGAPORE_SVG_MAP_FIX.md`, `docs/V6_4_3_SINGAPORE_MAP_ZOOM_HQ_REDESIGN.md`, `docs/V6_4_2_ACCURATE_SINGAPORE_MAP_NO_OVERLAY.md`, `docs/V6_4_1_SINGAPORE_TACTICAL_MAP_UI_POLISH.md`, `docs/V6_4_SINGAPORE_MISSION_MAP.md`, `docs/V6_3_SALES_COLLECTION_COMMAND_CENTRE.md`, `DEV_BRAIN_QA_REPORT.md`, `reports/V6_1_TEST_LEAD_CLEANUP_REPORT.md`, `reports/V6_ULTIMATE_DEEP_QA_REPORT.md`, `docs/V6_1_UI_POLISH_TEST_CLEANUP.md`, `docs/V6_ULTIMATE_SALES_COMMAND_CENTRE.md`, `docs/V6_ULTIMATE_BLUEPRINT.md`, `reports/V6_HUMAN_LIKE_SALES_BRAIN_DEEP_QA_REPORT.md`, and `V4_10_WHATSAPP_LIVE_PASS_REPORT.md`.",
  "",
  "## Tests / Audit Status",
  "",
  `Status: ${status}`,
  `Browser QA: ${browserStatus}`,
  "",
  "## Open Issues",
  "",
  ...openIssues.map((issue) => `- ${issue}`),
  "",
  "## Safety Status",
  "",
  "- OpenAI WhatsApp reply is off by default.",
  "- Fallback WhatsApp replies still work without OpenAI.",
  "- v5.2 question bank covers common homeowner questions through structured intents, examples, strategies, safety rules, and reply variations.",
  "- v5.3 adds a central reply decision engine, reply coach, quality gate, no-silence guard, and black box reply trace.",
  "- v5.3.1 adds multi-intent detection, lead context memory, repeated-info avoidance, and portfolio/Instagram routing.",
  "- v5.3.2 adds deep WhatsApp QA, media/floor-plan context repair, voice fallback without transcription, Singlish intent support with English replies, and server-only handoff email tracing.",
  "- v6.0 adds a Context Truth Gate, Singapore renovation meaning parser, natural reply composer, Safety Governor, Reply Quality Judge, and 150+ case deep QA.",
  "- v6 Ultimate adds safe cleanup, soft delete/restore, boss/admin hard-delete gating, human takeover, bot pause/resume, mission queue, lead scoring, follow-up reminders, role permissions, settings proof, gold command centre UI, QA centre, sales learning foundation, and quotation readiness foundation.",
  "- v6.1 polishes the premium command centre colour palette, increases readability, improves dashboard/lead/settings/report UX, and adds a dry-run-first old test lead cleanup script.",
  "- v6.3 adds manual Sales Pipeline, Sales & Collection, Targets, Boss Monthly Report, manual quotation tracking, project accounts, and payment/collection tracking.",
  "- v6.4 adds a privacy-safe Singapore Mission Map with a local static area/postal parser, hybrid area heatmap, clickable pins, unknown-area count, and sales/collection map layers where data exists.",
  "- v6.4.1 polishes the map UI into a stylised Singapore tactical map with inline silhouette, compact empty state, integrated legend, heat halos, mission pins, and area summary panel.",
  "- v6.4.2 improves the map base to a more accurate Singapore outline and removes the blocking empty-state overlay so the map remains visible even without mapped lead data.",
  "- v6.4.3 widens the map, adds zoom/pan/reset controls, keeps only the main island plus Sentosa, adds a privacy-safe LIMM HQ marker at postal `228397`, and fixes gold/amber visual separation.",
  "- v6.4.4 replaces the weak blob-like island path with a dedicated local Singapore SVG layer, keeps only the mainland plus one small Sentosa, and positions LIMM HQ on the central main island.",
  "- v6.5 adds Smart Lead Intake, missing-info detection, a 3-5 next-question cap, lifestyle/occupants/helper/pets/safety fields, budget expectation collection without price replies, timeline/key/move-in collection, Meeting Readiness, Proposal Readiness, lead profile storage, and audit trace.",
  "- v6.5.1 refines the Singapore map with a more accurate local static outline, calibrated HQ marker around Orchard/Dhoby Ghaut, smaller island-shaped Sentosa, faint area labels, and no large helper box.",
  "- Question bank replies include non-repetition handling, escalation rules, and audit metadata.",
  "- WhatsApp live inbound and auto-reply are confirmed PASS for Marcus-approved live mode.",
  "- Public WhatsApp auto-reply is allowed only for Marcus-approved live mode and remains safety-gated.",
  "- Google Calendar live booking remains disabled.",
  "- Calendar booking foundation requires boss approval and cannot confirm booking before an event exists.",
  "- Auto pricing and amount ranges remain blocked.",
  "- Review route is development-only and disabled by default unless NEXT_PUBLIC_ENABLE_REVIEW_ROUTE=true.",
  "- Secrets and .env values are not printed.",
  "",
  "## Auth Status",
  "",
  authStatus,
  "",
  "## Browser QA Status",
  "",
  browserStatus,
  data?.browserReport ? `Report: ${data.browserReport}` : "Report: not generated.",
  "",
  "## Next Recommended Action",
  "",
  nextAction,
  "",
  "## Marcus Paste Block For ChatGPT",
  "",
  "```text",
  "We are continuing LIMM AI Sales Command Centre after v6.5.1 Accurate Singapore Map Refinement.",
  `Latest Dev Brain QA status: ${status}.`,
  browserStatus,
  authStatus,
  "Confirmed live result: inbound WhatsApp received, lead created, lead visible, audit logs written, and WhatsApp auto-reply sent successfully.",
  "v5.3 fixes the live silence issue by changing the old 3-in-10-min auto-reply gate into a warning, then forcing valid client text through the reply coach, safety/quality/repetition gates, and a no-silence fallback.",
  "v5.3.1 improves reply intelligence for multi-question messages, avoids asking again for details already received, and routes portfolio/past-work requests to configured Instagram only.",
  "v5.3.2 fixes media context so floor plan images/documents can prevent repeated floor-plan requests, adds voice fallback without transcription, understands common Singlish-style intent while replying in professional English, and records/sends handoff email alerts to limmwork@gmail.com when configured.",
  "v6.0 improves reply quality with a Context Truth Gate, Singapore renovation shorthand understanding, natural replies, a strict Safety Governor, and a Reply Quality Judge. It specifically blocks over-claimed context and generic route-style replies for normal renovation questions.",
  "v6 Ultimate adds soft delete/restore/hard-delete safety, human takeover/bot pause, lead scoring, mission queue, settings/QA centre, gold command centre UI, sales learning foundation, weekly boss report draft foundation, and quotation/site visit readiness foundation.",
  "v6.1 adds premium UI/readability polish and a safe old test-lead cleanup workflow. Cleanup dry-run is default; apply requires --apply; hard delete remains explicit, boss/admin-only in app logic, and only for already-soft-deleted test data.",
  "v6.3 adds manual Sales Pipeline, Sales & Collection, Targets, Boss Monthly Report, manual quotation tracking, project account records, payment collection tracking, and non-GST proof.",
  "v6.4 adds a privacy-safe Singapore Mission Map with local static Singapore area/postal parsing, hybrid area heatmap, clickable pins, unknown-area count, no external geocoding/map key, and no full exact address on the main dashboard map.",
  "v6.4.1 replaces the generic oval/radar map visual with a stylised Singapore silhouette, compact premium empty state, integrated legend, heat halos, clickable mission pins, and a small area summary panel.",
  "v6.4.2 upgrades that visual to a more accurate Singapore outline and removes the large blocking empty-state overlay so the map base stays visible even with no data.",
  "v6.4.3 widens the Singapore map, adds zoom/pan/reset controls, keeps only the main island plus Sentosa, adds a privacy-safe LIMM HQ marker at postal 228397, and fixes gold/amber colour separation.",
  "v6.4.4 replaces the weak blob-like island path with a dedicated local Singapore SVG layer, keeps only the mainland plus one small Sentosa, and positions LIMM HQ on central Singapore instead of below the island.",
  "v6.5 adds Smart Lead Intake, missing-info detection, a 3-5 next-question cap, lifestyle/occupants/helper/pets/safety fields, budget expectation collection without price replies, timeline/key/move-in collection, Meeting Readiness, Proposal Readiness, lead profile storage, and audit trace.",
  "v6.5.1 refines the Singapore map with a more accurate local static outline, calibrated HQ marker around Orchard/Dhoby Ghaut, smaller island-shaped Sentosa, faint area labels, and no large helper box.",
  "OpenAI WhatsApp reply is off by default. Calendar booking and auto booking remain disabled by default. No pricing, quote ranges, blasting, or booking confirmation before event exists.",
  "Please review docs/V6_5_1_ACCURATE_SINGAPORE_MAP_REFINEMENT.md and use the health endpoint first before Marcus judges the deployed dashboard map.",
  "```",
  ""
].join("\n");

fs.writeFileSync(path.join(root, "CHATGPT_HANDOFF_REPORT.md"), report, "utf8");
console.log("Generated CHATGPT_HANDOFF_REPORT.md");
